direction: right

aoi: AllOverIt
aoi.alloverit-aws-cdk-appsync: AllOverIt.Aws.Cdk.AppSync
amazon-cdk-aws-appsync_1-204-0: Amazon.CDK.AWS.AppSync\nv1.204.0
amazon-cdk-aws-appsync_1-204-0.style.fill: "#ADD8E6"
amazon-cdk-aws-appsync_1-204-0.style.opacity: 0.8
amazon-cdk-aws-certificatemanager_1-204-0: Amazon.CDK.AWS.CertificateManager\nv1.204.0
amazon-cdk-aws-certificatemanager_1-204-0.style.fill: "#FFEC96"
amazon-cdk-aws-certificatemanager_1-204-0.style.opacity: 0.8
amazon-cdk-aws-certificatemanager_1-204-0 <- amazon-cdk-aws-appsync_1-204-0
amazon-cdk-aws-cognito_1-204-0: Amazon.CDK.AWS.Cognito\nv1.204.0
amazon-cdk-aws-cognito_1-204-0.style.fill: "#FFEC96"
amazon-cdk-aws-cognito_1-204-0.style.opacity: 0.8
amazon-cdk-aws-cognito_1-204-0 <- amazon-cdk-aws-appsync_1-204-0
amazon-cdk-aws-dynamodb_1-204-0: Amazon.CDK.AWS.DynamoDB\nv1.204.0
amazon-cdk-aws-dynamodb_1-204-0.style.fill: "#FFEC96"
amazon-cdk-aws-dynamodb_1-204-0.style.opacity: 0.8
amazon-cdk-aws-dynamodb_1-204-0 <- amazon-cdk-aws-appsync_1-204-0
amazon-cdk-aws-ec2_1-204-0: Amazon.CDK.AWS.EC2\nv1.204.0
amazon-cdk-aws-ec2_1-204-0.style.fill: "#FFEC96"
amazon-cdk-aws-ec2_1-204-0.style.opacity: 0.8
amazon-cdk-aws-ec2_1-204-0 <- amazon-cdk-aws-appsync_1-204-0
amazon-cdk-aws-elasticsearch_1-204-0: Amazon.CDK.AWS.Elasticsearch\nv1.204.0
amazon-cdk-aws-elasticsearch_1-204-0.style.fill: "#FFEC96"
amazon-cdk-aws-elasticsearch_1-204-0.style.opacity: 0.8
amazon-cdk-aws-elasticsearch_1-204-0 <- amazon-cdk-aws-appsync_1-204-0
amazon-cdk-aws-iam_1-204-0: Amazon.CDK.AWS.IAM\nv1.204.0
amazon-cdk-aws-iam_1-204-0.style.fill: "#FFEC96"
amazon-cdk-aws-iam_1-204-0.style.opacity: 0.8
amazon-cdk-aws-iam_1-204-0 <- amazon-cdk-aws-appsync_1-204-0
amazon-cdk-aws-lambda_1-204-0: Amazon.CDK.AWS.Lambda\nv1.204.0
amazon-cdk-aws-lambda_1-204-0.style.fill: "#FFEC96"
amazon-cdk-aws-lambda_1-204-0.style.opacity: 0.8
amazon-cdk-aws-lambda_1-204-0 <- amazon-cdk-aws-appsync_1-204-0
amazon-cdk-aws-opensearchservice_1-204-0: Amazon.CDK.AWS.OpenSearchService\nv1.204.0
amazon-cdk-aws-opensearchservice_1-204-0.style.fill: "#FFEC96"
amazon-cdk-aws-opensearchservice_1-204-0.style.opacity: 0.8
amazon-cdk-aws-opensearchservice_1-204-0 <- amazon-cdk-aws-appsync_1-204-0
amazon-cdk-aws-rds_1-204-0: Amazon.CDK.AWS.RDS\nv1.204.0
amazon-cdk-aws-rds_1-204-0.style.fill: "#FFEC96"
amazon-cdk-aws-rds_1-204-0.style.opacity: 0.8
amazon-cdk-aws-rds_1-204-0 <- amazon-cdk-aws-appsync_1-204-0
amazon-cdk-aws-s3-assets_1-204-0: Amazon.CDK.AWS.S3.Assets\nv1.204.0
amazon-cdk-aws-s3-assets_1-204-0.style.fill: "#FFEC96"
amazon-cdk-aws-s3-assets_1-204-0.style.opacity: 0.8
amazon-cdk-aws-s3-assets_1-204-0 <- amazon-cdk-aws-appsync_1-204-0
amazon-cdk-aws-secretsmanager_1-204-0: Amazon.CDK.AWS.SecretsManager\nv1.204.0
amazon-cdk-aws-secretsmanager_1-204-0.style.fill: "#FFEC96"
amazon-cdk-aws-secretsmanager_1-204-0.style.opacity: 0.8
amazon-cdk-aws-secretsmanager_1-204-0 <- amazon-cdk-aws-appsync_1-204-0
amazon-cdk_1-204-0: Amazon.CDK\nv1.204.0
amazon-cdk_1-204-0.style.fill: "#FFEC96"
amazon-cdk_1-204-0.style.opacity: 0.8
amazon-cdk_1-204-0 <- amazon-cdk-aws-appsync_1-204-0
amazon-jsii-runtime_1-84-0: Amazon.JSII.Runtime\nv1.84.0
amazon-jsii-runtime_1-84-0.style.fill: "#FFEC96"
amazon-jsii-runtime_1-84-0.style.opacity: 0.8
amazon-jsii-runtime_1-84-0 <- amazon-cdk-aws-appsync_1-204-0
constructs_3-3-69: Constructs\nv3.3.69
constructs_3-3-69.style.fill: "#FFEC96"
constructs_3-3-69.style.opacity: 0.8
constructs_3-3-69 <- amazon-cdk-aws-appsync_1-204-0
amazon-cdk-aws-appsync_1-204-0 <- aoi.alloverit-aws-cdk-appsync
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-aws-cdk-appsync
