direction: right

aoi: AllOverIt
aoi.alloverit-serialization-json-systemtext: AllOverIt.Serialization.Json.SystemText
aoi.alloverit-serialization-json-abstractions: AllOverIt.Serialization.Json.Abstractions
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
system-text-json: System.Text.Json
system-text-json.style.fill: lightblue
system-text-json.style.opacity: 0.8

aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-serialization-json-systemtext
aoi.alloverit <- aoi.alloverit-serialization-json-abstractions
aoi.alloverit-assertion <- aoi.alloverit
system-text-json <- aoi.alloverit-serialization-json-systemtext
