direction: right

aoi: AllOverIt
aoi.alloverit-aspnetcore: AllOverIt.AspNetCore
microsoft-aspnetcore-mvc: Microsoft.AspNetCore.Mvc
microsoft-aspnetcore-mvc.style.fill: "#ADD8E6"
microsoft-aspnetcore-mvc.style.opacity: 0.8
microsoft-aspnetcore-mvc-analyzers: Microsoft.AspNetCore.Mvc.Analyzers
microsoft-aspnetcore-mvc-analyzers.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-analyzers.style.opacity: 0.8
microsoft-aspnetcore-mvc-analyzers <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-apiexplorer: Microsoft.AspNetCore.Mvc.ApiExplorer
microsoft-aspnetcore-mvc-apiexplorer.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-apiexplorer.style.opacity: 0.8
microsoft-aspnetcore-mvc-apiexplorer <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-cors: Microsoft.AspNetCore.Mvc.Cors
microsoft-aspnetcore-mvc-cors.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-cors.style.opacity: 0.8
microsoft-aspnetcore-mvc-cors <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-dataannotations: Microsoft.AspNetCore.Mvc.DataAnnotations
microsoft-aspnetcore-mvc-dataannotations.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-dataannotations.style.opacity: 0.8
microsoft-aspnetcore-mvc-dataannotations <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-formatters-json: Microsoft.AspNetCore.Mvc.Formatters.Json
microsoft-aspnetcore-mvc-formatters-json.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-formatters-json.style.opacity: 0.8
microsoft-aspnetcore-mvc-formatters-json <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-localization: Microsoft.AspNetCore.Mvc.Localization
microsoft-aspnetcore-mvc-localization.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-localization.style.opacity: 0.8
microsoft-aspnetcore-mvc-localization <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-razorpages: Microsoft.AspNetCore.Mvc.RazorPages
microsoft-aspnetcore-mvc-razorpages.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-razorpages.style.opacity: 0.8
microsoft-aspnetcore-mvc-razorpages <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-taghelpers: Microsoft.AspNetCore.Mvc.TagHelpers
microsoft-aspnetcore-mvc-taghelpers.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-taghelpers.style.opacity: 0.8
microsoft-aspnetcore-mvc-taghelpers <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-viewfeatures: Microsoft.AspNetCore.Mvc.ViewFeatures
microsoft-aspnetcore-mvc-viewfeatures.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-viewfeatures.style.opacity: 0.8
microsoft-aspnetcore-mvc-viewfeatures <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-razor-extensions: Microsoft.AspNetCore.Mvc.Razor.Extensions
microsoft-aspnetcore-mvc-razor-extensions.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-razor-extensions.style.opacity: 0.8
microsoft-aspnetcore-mvc-razor-extensions <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-razor-design: Microsoft.AspNetCore.Razor.Design
microsoft-aspnetcore-razor-design.style.fill: "#FFEC96"
microsoft-aspnetcore-razor-design.style.opacity: 0.8
microsoft-aspnetcore-razor-design <- microsoft-aspnetcore-mvc
microsoft-extensions-caching-memory: Microsoft.Extensions.Caching.Memory
microsoft-extensions-caching-memory.style.fill: "#FFEC96"
microsoft-extensions-caching-memory.style.opacity: 0.8
microsoft-extensions-caching-memory <- microsoft-aspnetcore-mvc
microsoft-extensions-dependencyinjection: Microsoft.Extensions.DependencyInjection
microsoft-extensions-dependencyinjection.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection.style.opacity: 0.8
microsoft-extensions-dependencyinjection <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc <- aoi.alloverit-aspnetcore
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-aspnetcore
