direction: right

aoi: AllOverIt
aoi.alloverit-fixture: AllOverIt.Fixture
autofixture_4-18-0: AutoFixture\nv4.18.0
autofixture_4-18-0.style.fill: "#ADD8E6"
autofixture_4-18-0.style.opacity: 0.8
fare_2-1-1: Fare\nv2.1.1
fare_2-1-1.style.fill: "#FFEC96"
fare_2-1-1.style.opacity: 0.8
fare_2-1-1 <- autofixture_4-18-0
system-componentmodel-annotations_4-3-0: System.ComponentModel.Annotations\nv4.3.0
system-componentmodel-annotations_4-3-0.style.fill: "#FFEC96"
system-componentmodel-annotations_4-3-0.style.opacity: 0.8
system-componentmodel-annotations_4-3-0 <- autofixture_4-18-0
autofixture_4-18-0 <- aoi.alloverit-fixture
fluentassertions_6-10-0: FluentAssertions\nv6.10.0
fluentassertions_6-10-0.style.fill: "#ADD8E6"
fluentassertions_6-10-0.style.opacity: 0.8
fluentassertions_6-10-0 <- aoi.alloverit-fixture
