direction: right

mal-smith: AllOverIt {
  aoi: AllOverIt
  aoi-aspnetcore: AllOverIt.AspNetCore
  aoi-assertion: AllOverIt.Assertion
  aoi-aws-appsync-client: AllOverIt.Aws.AppSync.Client
  aoi-aws-cdk-appsync: AllOverIt.Aws.Cdk.AppSync
  aoi-csv: AllOverIt.Csv
  aoi-dependencyinjection: AllOverIt.DependencyInjection
  aoi-entityframeworkcore: AllOverIt.EntityFrameworkCore
  aoi-entityframeworkcore-diagrams: AllOverIt.EntityFrameworkCore.Diagrams
  aoi-entityframeworkcore-pagination: AllOverIt.EntityFrameworkCore.Pagination
  aoi-evaluator: AllOverIt.Evaluator
  aoi-filtering: AllOverIt.Filtering
  aoi-fixture: AllOverIt.Fixture
  aoi-fixture-fakeiteasy: AllOverIt.Fixture.FakeItEasy
  aoi-generichost: AllOverIt.GenericHost
  aoi-mapping: AllOverIt.Mapping
  aoi-pagination: AllOverIt.Pagination
  aoi-reactive: AllOverIt.Reactive
  aoi-reactiveui: AllOverIt.ReactiveUI
  aoi-serialization-binary: AllOverIt.Serialization.Binary
  aoi-serialization-json-abstractions: AllOverIt.Serialization.Json.Abstractions
  aoi-serialization-json-newtonsoft: AllOverIt.Serialization.Json.NewtonSoft
  aoi-serialization-json-systemtext: AllOverIt.Serialization.Json.SystemText
  aoi-validation: AllOverIt.Validation
  aoi-validation-options: AllOverIt.Validation.Options
}

msft: Microsoft {
  style: {
    fill: "lightblue"
    opacity: 0.8
  }

  msft-aspnetcore-mvc: Microsoft.AspNetCore.Mvc
  msft-extensions-dependencyinjection: Microsoft.Extensions.DependencyInjection
  msft-extensions-dependencyinjection-abstractions: Microsoft.Extensions.DependencyInjection.Abstractions
  msft-extensions-http: Microsoft.Extensions.Http
  msft-extensions-hosting: Microsoft.Extensions.Hosting
  msft-extensions-options: Microsoft.Extensions.Options
  msft-entityframeworkcore-relational: Microsoft.EntityFrameworkCore.Relational
  system-text-json: System.Text.Json
}

dotnet-foundation: .Net Foundation {
  style: {
    fill: "lightblue"
    opacity: 0.8
  }

  system-reactive: System.Reactive
  reactiveui: ReactiveUI
  reactiveui-fody: ReactiveUI.Fody
}

amazon: Amazon {
  style: {
    fill: "lightblue"
    opacity: 0.8
  }

  amazon-cdk-aws-appsync: Amazon.CDK.AWS.AppSync
}

csvhelper: CsvHelper {
  style: {
    fill: "lightblue"
    opacity: 0.8
  }

  csvhelper: CsvHelper
}

autofixture: AutoFixture {
  style: {
    fill: "lightblue"
    opacity: 0.8
  }

  autofixture: AutoFixture
  autofixture-autofakeiteasy: AutoFixture.AutoFakeItEasy
}

fluentassertions: FluentAssertions {
  style: {
    fill: "lightblue"
    opacity: 0.8
  }

  fluentassertions: FluentAssertions
}

fluentvalidation: FluentValidation {
  style: {
    fill: "lightblue"
    opacity: 0.8
  }

  fluentvalidation: FluentValidation
}

fakeiteasy: FakeItEasy {
  style: {
    fill: "lightblue"
    opacity: 0.8
  }

  fakeiteasy: FakeItEasy
}

newtonsoft: Newtonsoft {
  style: {
    fill: "lightblue"
    opacity: 0.8
  }

  newtonsoft-json: Newtonsoft.Json
}

# AllOverIt
mal-smith.aoi-assertion <- mal-smith.aoi

# AllOverIt.AspNetCore
mal-smith.aoi <- mal-smith.aoi-aspnetcore
msft.msft-aspnetcore-mvc <- mal-smith.aoi-aspnetcore

# AllOverIt.Assertion

# AllOverIt.Aws.AppSync.Client
mal-smith.aoi-reactive <- mal-smith.aoi-aws-appsync-client
mal-smith.aoi-serialization-json-abstractions <- mal-smith.aoi-aws-appsync-client
msft.msft-extensions-dependencyinjection <- mal-smith.aoi-aws-appsync-client
msft.msft-extensions-http <- mal-smith.aoi-aws-appsync-client

# AllOverIt.Aws.Cdk.AppSync
mal-smith.aoi <- mal-smith.aoi-aws-cdk-appsync
amazon.amazon-cdk-aws-appsync <- mal-smith.aoi-aws-cdk-appsync

# AllOverIt.Csv
mal-smith.aoi <- mal-smith.aoi-csv
csvhelper.csvhelper <- mal-smith.aoi-csv

# AllOverIt.DependencyInjection
mal-smith.aoi <- mal-smith.aoi-dependencyinjection
msft.msft-extensions-dependencyinjection-abstractions <- mal-smith.aoi-dependencyinjection

# AllOverIt.EntityFrameworkCore
mal-smith.aoi <- mal-smith.aoi-entityframeworkcore
msft.msft-entityframeworkcore-relational <- mal-smith.aoi-entityframeworkcore

# AllOverIt.EntityFrameworkCore.Diagrams
mal-smith.aoi <- mal-smith.aoi-entityframeworkcore-diagrams
msft.msft-entityframeworkcore-relational <- mal-smith.aoi-entityframeworkcore-diagrams

# AllOverIt.EntityFrameworkCore.Pagination
mal-smith.aoi-entityframeworkcore <- mal-smith.aoi-entityframeworkcore-pagination
mal-smith.aoi-pagination <- mal-smith.aoi-entityframeworkcore-pagination

# AllOverIt.Evaluator
mal-smith.aoi <- mal-smith.aoi-evaluator

# AllOverIt.Filtering
mal-smith.aoi <- mal-smith.aoi-filtering

# AllOverIt.Fixture
autofixture.autofixture <- mal-smith.aoi-fixture
fluentassertions.fluentassertions <- mal-smith.aoi-fixture

# AllOverIt.Fixture.FakeItEasy
mal-smith.aoi-fixture <- mal-smith.aoi-fixture-fakeiteasy
fakeiteasy.fakeiteasy <- mal-smith.aoi-fixture-fakeiteasy
autofixture.autofixture-autofakeiteasy <- mal-smith.aoi-fixture-fakeiteasy

# AllOverIt.GenericHost
mal-smith.aoi <- mal-smith.aoi-generichost
msft.msft-extensions-hosting <- mal-smith.aoi-generichost

# AllOverIt.Mapping
mal-smith.aoi <- mal-smith.aoi-mapping

# AllOverIt.Pagination
mal-smith.aoi-serialization-binary <- mal-smith.aoi-pagination
msft.msft-extensions-dependencyinjection-abstractions <- mal-smith.aoi-pagination

# AllOverIt.Reactive
mal-smith.aoi <- mal-smith.aoi-reactive
dotnet-foundation.system-reactive <- mal-smith.aoi-reactive

# AllOverIt.ReactiveUI
mal-smith.aoi <- mal-smith.aoi-reactiveui
msft.msft-extensions-dependencyinjection-abstractions <- mal-smith.aoi-reactiveui
dotnet-foundation.reactiveui <- mal-smith.aoi-reactiveui
dotnet-foundation.reactiveui-fody <- mal-smith.aoi-reactiveui

# AllOverIt.Serialization.Binary
mal-smith.aoi <- mal-smith.aoi-serialization-binary

# AllOverIt.Serialization.Json.Abstractions
mal-smith.aoi <- mal-smith.aoi-serialization-json-abstractions

# AllOverIt.Serialization.Json.NewtonSoft
mal-smith.aoi-serialization-json-abstractions <- mal-smith.aoi-serialization-json-newtonsoft
newtonsoft.newtonsoft-json <- mal-smith.aoi-serialization-json-newtonsoft

# AllOverIt.Serialization.Json.SystemText
mal-smith.aoi-serialization-json-abstractions <- mal-smith.aoi-serialization-json-systemtext
msft.system-text-json <- mal-smith.aoi-serialization-json-systemtext

# AllOverIt.Validation
mal-smith.aoi <- mal-smith.aoi-validation
fluentvalidation.fluentvalidation <- mal-smith.aoi-validation

# AllOverIt.Validation.Options
mal-smith.aoi-validation <- mal-smith.aoi-validation-options
msft.msft-extensions-options <- mal-smith.aoi-validation-options
