direction: right

aoi: AllOverIt
aoi.alloverit-serialization-json-abstractions: AllOverIt.Serialization.Json.Abstractions
aoi.alloverit: AllOverIt

aoi.alloverit <- aoi.alloverit-serialization-json-abstractions
