direction: right

aoi: AllOverIt
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-fixture: AllOverIt.Fixture
autofixture: AutoFixture
autofixture.style.fill: lightblue
autofixture.style.opacity: 0.8
fare: Fare
fare.style.fill: lightblue
fare.style.opacity: 0.8
system-componentmodel-annotations: System.ComponentModel.Annotations
system-componentmodel-annotations.style.fill: lightblue
system-componentmodel-annotations.style.opacity: 0.8
fluentassertions: FluentAssertions
fluentassertions.style.fill: lightblue
fluentassertions.style.opacity: 0.8
aoi.alloverit-evaluator: AllOverIt.Evaluator
aoi.alloverit-fixture-fakeiteasy: AllOverIt.Fixture.FakeItEasy
autofixture-autofakeiteasy: AutoFixture.AutoFakeItEasy
autofixture-autofakeiteasy.style.fill: lightblue
autofixture-autofakeiteasy.style.opacity: 0.8
fakeiteasy: FakeItEasy
fakeiteasy.style.fill: lightblue
fakeiteasy.style.opacity: 0.8
castle-core: Castle.Core
castle-core.style.fill: lightblue
castle-core.style.opacity: 0.8
aoi.alloverit-aws-cdk-appsync: AllOverIt.Aws.Cdk.AppSync
amazon-cdk-aws-appsync: Amazon.CDK.AWS.AppSync
amazon-cdk-aws-appsync.style.fill: lightblue
amazon-cdk-aws-appsync.style.opacity: 0.8
amazon-cdk-aws-certificatemanager: Amazon.CDK.AWS.CertificateManager
amazon-cdk-aws-certificatemanager.style.fill: lightblue
amazon-cdk-aws-certificatemanager.style.opacity: 0.8
amazon-cdk-aws-cognito: Amazon.CDK.AWS.Cognito
amazon-cdk-aws-cognito.style.fill: lightblue
amazon-cdk-aws-cognito.style.opacity: 0.8
amazon-cdk-aws-dynamodb: Amazon.CDK.AWS.DynamoDB
amazon-cdk-aws-dynamodb.style.fill: lightblue
amazon-cdk-aws-dynamodb.style.opacity: 0.8
amazon-cdk-aws-ec2: Amazon.CDK.AWS.EC2
amazon-cdk-aws-ec2.style.fill: lightblue
amazon-cdk-aws-ec2.style.opacity: 0.8
amazon-cdk-aws-elasticsearch: Amazon.CDK.AWS.Elasticsearch
amazon-cdk-aws-elasticsearch.style.fill: lightblue
amazon-cdk-aws-elasticsearch.style.opacity: 0.8
amazon-cdk-aws-iam: Amazon.CDK.AWS.IAM
amazon-cdk-aws-iam.style.fill: lightblue
amazon-cdk-aws-iam.style.opacity: 0.8
amazon-cdk-aws-lambda: Amazon.CDK.AWS.Lambda
amazon-cdk-aws-lambda.style.fill: lightblue
amazon-cdk-aws-lambda.style.opacity: 0.8
amazon-cdk-aws-opensearchservice: Amazon.CDK.AWS.OpenSearchService
amazon-cdk-aws-opensearchservice.style.fill: lightblue
amazon-cdk-aws-opensearchservice.style.opacity: 0.8
amazon-cdk-aws-rds: Amazon.CDK.AWS.RDS
amazon-cdk-aws-rds.style.fill: lightblue
amazon-cdk-aws-rds.style.opacity: 0.8
amazon-cdk-aws-s3-assets: Amazon.CDK.AWS.S3.Assets
amazon-cdk-aws-s3-assets.style.fill: lightblue
amazon-cdk-aws-s3-assets.style.opacity: 0.8
amazon-cdk-aws-secretsmanager: Amazon.CDK.AWS.SecretsManager
amazon-cdk-aws-secretsmanager.style.fill: lightblue
amazon-cdk-aws-secretsmanager.style.opacity: 0.8
amazon-cdk: Amazon.CDK
amazon-cdk.style.fill: lightblue
amazon-cdk.style.opacity: 0.8
amazon-jsii-runtime: Amazon.JSII.Runtime
amazon-jsii-runtime.style.fill: lightblue
amazon-jsii-runtime.style.opacity: 0.8
constructs: Constructs
constructs.style.fill: lightblue
constructs.style.opacity: 0.8
aoi.alloverit-generichost: AllOverIt.GenericHost
microsoft-extensions-hosting: Microsoft.Extensions.Hosting
microsoft-extensions-hosting.style.fill: lightblue
microsoft-extensions-hosting.style.opacity: 0.8
microsoft-extensions-configuration-abstractions: Microsoft.Extensions.Configuration.Abstractions
microsoft-extensions-configuration-abstractions.style.fill: lightblue
microsoft-extensions-configuration-abstractions.style.opacity: 0.8
microsoft-extensions-configuration-binder: Microsoft.Extensions.Configuration.Binder
microsoft-extensions-configuration-binder.style.fill: lightblue
microsoft-extensions-configuration-binder.style.opacity: 0.8
microsoft-extensions-configuration-commandline: Microsoft.Extensions.Configuration.CommandLine
microsoft-extensions-configuration-commandline.style.fill: lightblue
microsoft-extensions-configuration-commandline.style.opacity: 0.8
microsoft-extensions-configuration-environmentvariables: Microsoft.Extensions.Configuration.EnvironmentVariables
microsoft-extensions-configuration-environmentvariables.style.fill: lightblue
microsoft-extensions-configuration-environmentvariables.style.opacity: 0.8
microsoft-extensions-configuration-fileextensions: Microsoft.Extensions.Configuration.FileExtensions
microsoft-extensions-configuration-fileextensions.style.fill: lightblue
microsoft-extensions-configuration-fileextensions.style.opacity: 0.8
microsoft-extensions-configuration-json: Microsoft.Extensions.Configuration.Json
microsoft-extensions-configuration-json.style.fill: lightblue
microsoft-extensions-configuration-json.style.opacity: 0.8
microsoft-extensions-configuration-usersecrets: Microsoft.Extensions.Configuration.UserSecrets
microsoft-extensions-configuration-usersecrets.style.fill: lightblue
microsoft-extensions-configuration-usersecrets.style.opacity: 0.8
microsoft-extensions-configuration: Microsoft.Extensions.Configuration
microsoft-extensions-configuration.style.fill: lightblue
microsoft-extensions-configuration.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions: Microsoft.Extensions.DependencyInjection.Abstractions
microsoft-extensions-dependencyinjection-abstractions.style.fill: lightblue
microsoft-extensions-dependencyinjection-abstractions.style.opacity: 0.8
microsoft-extensions-dependencyinjection: Microsoft.Extensions.DependencyInjection
microsoft-extensions-dependencyinjection.style.fill: lightblue
microsoft-extensions-dependencyinjection.style.opacity: 0.8
microsoft-extensions-fileproviders-abstractions: Microsoft.Extensions.FileProviders.Abstractions
microsoft-extensions-fileproviders-abstractions.style.fill: lightblue
microsoft-extensions-fileproviders-abstractions.style.opacity: 0.8
microsoft-extensions-fileproviders-physical: Microsoft.Extensions.FileProviders.Physical
microsoft-extensions-fileproviders-physical.style.fill: lightblue
microsoft-extensions-fileproviders-physical.style.opacity: 0.8
microsoft-extensions-hosting-abstractions: Microsoft.Extensions.Hosting.Abstractions
microsoft-extensions-hosting-abstractions.style.fill: lightblue
microsoft-extensions-hosting-abstractions.style.opacity: 0.8
microsoft-extensions-logging-abstractions: Microsoft.Extensions.Logging.Abstractions
microsoft-extensions-logging-abstractions.style.fill: lightblue
microsoft-extensions-logging-abstractions.style.opacity: 0.8
microsoft-extensions-logging-configuration: Microsoft.Extensions.Logging.Configuration
microsoft-extensions-logging-configuration.style.fill: lightblue
microsoft-extensions-logging-configuration.style.opacity: 0.8
microsoft-extensions-logging-console: Microsoft.Extensions.Logging.Console
microsoft-extensions-logging-console.style.fill: lightblue
microsoft-extensions-logging-console.style.opacity: 0.8
microsoft-extensions-logging-debug: Microsoft.Extensions.Logging.Debug
microsoft-extensions-logging-debug.style.fill: lightblue
microsoft-extensions-logging-debug.style.opacity: 0.8
microsoft-extensions-logging-eventlog: Microsoft.Extensions.Logging.EventLog
microsoft-extensions-logging-eventlog.style.fill: lightblue
microsoft-extensions-logging-eventlog.style.opacity: 0.8
microsoft-extensions-logging-eventsource: Microsoft.Extensions.Logging.EventSource
microsoft-extensions-logging-eventsource.style.fill: lightblue
microsoft-extensions-logging-eventsource.style.opacity: 0.8
microsoft-extensions-logging: Microsoft.Extensions.Logging
microsoft-extensions-logging.style.fill: lightblue
microsoft-extensions-logging.style.opacity: 0.8
microsoft-extensions-options: Microsoft.Extensions.Options
microsoft-extensions-options.style.fill: lightblue
microsoft-extensions-options.style.opacity: 0.8
system-diagnostics-diagnosticsource: System.Diagnostics.DiagnosticSource
system-diagnostics-diagnosticsource.style.fill: lightblue
system-diagnostics-diagnosticsource.style.opacity: 0.8
aoi.alloverit-validation: AllOverIt.Validation
fluentvalidation: FluentValidation
fluentvalidation.style.fill: lightblue
fluentvalidation.style.opacity: 0.8
aoi.alloverit-aws-appsync-client: AllOverIt.Aws.AppSync.Client
aoi.alloverit-reactive: AllOverIt.Reactive
aoi.alloverit-serialization-json-abstractions: AllOverIt.Serialization.Json.Abstractions
microsoft-extensions-http: Microsoft.Extensions.Http
microsoft-extensions-http.style.fill: lightblue
microsoft-extensions-http.style.opacity: 0.8
aoi.alloverit-aspnetcore: AllOverIt.AspNetCore
microsoft-aspnetcore-mvc: Microsoft.AspNetCore.Mvc
microsoft-aspnetcore-mvc.style.fill: lightblue
microsoft-aspnetcore-mvc.style.opacity: 0.8
microsoft-aspnetcore-mvc-analyzers: Microsoft.AspNetCore.Mvc.Analyzers
microsoft-aspnetcore-mvc-analyzers.style.fill: lightblue
microsoft-aspnetcore-mvc-analyzers.style.opacity: 0.8
microsoft-aspnetcore-mvc-apiexplorer: Microsoft.AspNetCore.Mvc.ApiExplorer
microsoft-aspnetcore-mvc-apiexplorer.style.fill: lightblue
microsoft-aspnetcore-mvc-apiexplorer.style.opacity: 0.8
microsoft-aspnetcore-mvc-cors: Microsoft.AspNetCore.Mvc.Cors
microsoft-aspnetcore-mvc-cors.style.fill: lightblue
microsoft-aspnetcore-mvc-cors.style.opacity: 0.8
microsoft-aspnetcore-mvc-dataannotations: Microsoft.AspNetCore.Mvc.DataAnnotations
microsoft-aspnetcore-mvc-dataannotations.style.fill: lightblue
microsoft-aspnetcore-mvc-dataannotations.style.opacity: 0.8
microsoft-aspnetcore-mvc-formatters-json: Microsoft.AspNetCore.Mvc.Formatters.Json
microsoft-aspnetcore-mvc-formatters-json.style.fill: lightblue
microsoft-aspnetcore-mvc-formatters-json.style.opacity: 0.8
microsoft-aspnetcore-mvc-localization: Microsoft.AspNetCore.Mvc.Localization
microsoft-aspnetcore-mvc-localization.style.fill: lightblue
microsoft-aspnetcore-mvc-localization.style.opacity: 0.8
microsoft-aspnetcore-mvc-razorpages: Microsoft.AspNetCore.Mvc.RazorPages
microsoft-aspnetcore-mvc-razorpages.style.fill: lightblue
microsoft-aspnetcore-mvc-razorpages.style.opacity: 0.8
microsoft-aspnetcore-mvc-taghelpers: Microsoft.AspNetCore.Mvc.TagHelpers
microsoft-aspnetcore-mvc-taghelpers.style.fill: lightblue
microsoft-aspnetcore-mvc-taghelpers.style.opacity: 0.8
microsoft-aspnetcore-mvc-viewfeatures: Microsoft.AspNetCore.Mvc.ViewFeatures
microsoft-aspnetcore-mvc-viewfeatures.style.fill: lightblue
microsoft-aspnetcore-mvc-viewfeatures.style.opacity: 0.8
microsoft-aspnetcore-mvc-razor-extensions: Microsoft.AspNetCore.Mvc.Razor.Extensions
microsoft-aspnetcore-mvc-razor-extensions.style.fill: lightblue
microsoft-aspnetcore-mvc-razor-extensions.style.opacity: 0.8
microsoft-aspnetcore-razor-design: Microsoft.AspNetCore.Razor.Design
microsoft-aspnetcore-razor-design.style.fill: lightblue
microsoft-aspnetcore-razor-design.style.opacity: 0.8
microsoft-extensions-caching-memory: Microsoft.Extensions.Caching.Memory
microsoft-extensions-caching-memory.style.fill: lightblue
microsoft-extensions-caching-memory.style.opacity: 0.8
aoi.alloverit-entityframeworkcore: AllOverIt.EntityFrameworkCore
microsoft-entityframeworkcore-relational: Microsoft.EntityFrameworkCore.Relational
microsoft-entityframeworkcore-relational.style.fill: lightblue
microsoft-entityframeworkcore-relational.style.opacity: 0.8
microsoft-entityframeworkcore: Microsoft.EntityFrameworkCore
microsoft-entityframeworkcore.style.fill: lightblue
microsoft-entityframeworkcore.style.opacity: 0.8
aoi.alloverit-csv: AllOverIt.Csv
csvhelper: CsvHelper
csvhelper.style.fill: lightblue
csvhelper.style.opacity: 0.8
microsoft-csharp: Microsoft.CSharp
microsoft-csharp.style.fill: lightblue
microsoft-csharp.style.opacity: 0.8
system-reactive: System.Reactive
system-reactive.style.fill: lightblue
system-reactive.style.opacity: 0.8
system-threading-tasks-extensions: System.Threading.Tasks.Extensions
system-threading-tasks-extensions.style.fill: lightblue
system-threading-tasks-extensions.style.opacity: 0.8
aoi.alloverit-dependencyinjection: AllOverIt.DependencyInjection
aoi.alloverit-pagination: AllOverIt.Pagination
aoi.alloverit-serialization-binary: AllOverIt.Serialization.Binary
aoi.alloverit-entityframeworkcore-pagination: AllOverIt.EntityFrameworkCore.Pagination
aoi.alloverit-reactiveui: AllOverIt.ReactiveUI
reactiveui: ReactiveUI
reactiveui.style.fill: lightblue
reactiveui.style.opacity: 0.8
dynamicdata: DynamicData
dynamicdata.style.fill: lightblue
dynamicdata.style.opacity: 0.8
splat: Splat
splat.style.fill: lightblue
splat.style.opacity: 0.8
system-componentmodel: System.ComponentModel
system-componentmodel.style.fill: lightblue
system-componentmodel.style.opacity: 0.8
system-diagnostics-contracts: System.Diagnostics.Contracts
system-diagnostics-contracts.style.fill: lightblue
system-diagnostics-contracts.style.opacity: 0.8
system-dynamic-runtime: System.Dynamic.Runtime
system-dynamic-runtime.style.fill: lightblue
system-dynamic-runtime.style.opacity: 0.8
system-runtime-serialization-primitives: System.Runtime.Serialization.Primitives
system-runtime-serialization-primitives.style.fill: lightblue
system-runtime-serialization-primitives.style.opacity: 0.8
reactiveui-fody: ReactiveUI.Fody
reactiveui-fody.style.fill: lightblue
reactiveui-fody.style.opacity: 0.8
fody: Fody
fody.style.fill: lightblue
fody.style.opacity: 0.8
aoi.alloverit-filtering: AllOverIt.Filtering
aoi.alloverit-validation-options: AllOverIt.Validation.Options
microsoft-extensions-primitives: Microsoft.Extensions.Primitives
microsoft-extensions-primitives.style.fill: lightblue
microsoft-extensions-primitives.style.opacity: 0.8
aoi.alloverit-entityframeworkcore-diagrams: AllOverIt.EntityFrameworkCore.Diagrams
aoi.alloverit-mapping: AllOverIt.Mapping
aoi.alloverit-serialization-json-newtonsoft: AllOverIt.Serialization.Json.Newtonsoft
newtonsoft-json: Newtonsoft.Json
newtonsoft-json.style.fill: lightblue
newtonsoft-json.style.opacity: 0.8
aoi.alloverit-serialization-json-systemtext: AllOverIt.Serialization.Json.SystemText
system-text-json: System.Text.Json
system-text-json.style.fill: lightblue
system-text-json.style.opacity: 0.8
microsoft-bcl-asyncinterfaces: Microsoft.Bcl.AsyncInterfaces
microsoft-bcl-asyncinterfaces.style.fill: lightblue
microsoft-bcl-asyncinterfaces.style.opacity: 0.8
system-text-encodings-web: System.Text.Encodings.Web
system-text-encodings-web.style.fill: lightblue
system-text-encodings-web.style.opacity: 0.8
system-buffers: System.Buffers
system-buffers.style.fill: lightblue
system-buffers.style.opacity: 0.8
system-memory: System.Memory
system-memory.style.fill: lightblue
system-memory.style.opacity: 0.8
system-numerics-vectors: System.Numerics.Vectors
system-numerics-vectors.style.fill: lightblue
system-numerics-vectors.style.opacity: 0.8
system-runtime-compilerservices-unsafe: System.Runtime.CompilerServices.Unsafe
system-runtime-compilerservices-unsafe.style.fill: lightblue
system-runtime-compilerservices-unsafe.style.opacity: 0.8
aoi.alloverit-wpf: AllOverIt.Wpf
aoi.alloverit-wpf-controls: AllOverIt.Wpf.Controls

aoi.alloverit-assertion <- aoi.alloverit
autofixture <- aoi.alloverit-fixture
fare <- autofixture
system-componentmodel-annotations <- autofixture
fluentassertions <- aoi.alloverit-fixture
aoi.alloverit <- aoi.alloverit-evaluator
aoi.alloverit-fixture <- aoi.alloverit-fixture-fakeiteasy
autofixture-autofakeiteasy <- aoi.alloverit-fixture-fakeiteasy
autofixture <- autofixture-autofakeiteasy
fakeiteasy <- autofixture-autofakeiteasy
fakeiteasy <- aoi.alloverit-fixture-fakeiteasy
castle-core <- fakeiteasy
aoi.alloverit <- aoi.alloverit-aws-cdk-appsync
amazon-cdk-aws-appsync <- aoi.alloverit-aws-cdk-appsync
amazon-cdk-aws-certificatemanager <- amazon-cdk-aws-appsync
amazon-cdk-aws-cognito <- amazon-cdk-aws-appsync
amazon-cdk-aws-dynamodb <- amazon-cdk-aws-appsync
amazon-cdk-aws-ec2 <- amazon-cdk-aws-appsync
amazon-cdk-aws-elasticsearch <- amazon-cdk-aws-appsync
amazon-cdk-aws-iam <- amazon-cdk-aws-appsync
amazon-cdk-aws-lambda <- amazon-cdk-aws-appsync
amazon-cdk-aws-opensearchservice <- amazon-cdk-aws-appsync
amazon-cdk-aws-rds <- amazon-cdk-aws-appsync
amazon-cdk-aws-s3-assets <- amazon-cdk-aws-appsync
amazon-cdk-aws-secretsmanager <- amazon-cdk-aws-appsync
amazon-cdk <- amazon-cdk-aws-appsync
amazon-jsii-runtime <- amazon-cdk-aws-appsync
constructs <- amazon-cdk-aws-appsync
aoi.alloverit <- aoi.alloverit-generichost
microsoft-extensions-hosting <- aoi.alloverit-generichost
microsoft-extensions-configuration-abstractions <- microsoft-extensions-hosting
microsoft-extensions-configuration-binder <- microsoft-extensions-hosting
microsoft-extensions-configuration-commandline <- microsoft-extensions-hosting
microsoft-extensions-configuration-environmentvariables <- microsoft-extensions-hosting
microsoft-extensions-configuration-fileextensions <- microsoft-extensions-hosting
microsoft-extensions-configuration-json <- microsoft-extensions-hosting
microsoft-extensions-configuration-usersecrets <- microsoft-extensions-hosting
microsoft-extensions-configuration <- microsoft-extensions-hosting
microsoft-extensions-dependencyinjection-abstractions <- microsoft-extensions-hosting
microsoft-extensions-dependencyinjection <- microsoft-extensions-hosting
microsoft-extensions-fileproviders-abstractions <- microsoft-extensions-hosting
microsoft-extensions-fileproviders-physical <- microsoft-extensions-hosting
microsoft-extensions-hosting-abstractions <- microsoft-extensions-hosting
microsoft-extensions-logging-abstractions <- microsoft-extensions-hosting
microsoft-extensions-logging-configuration <- microsoft-extensions-hosting
microsoft-extensions-logging-console <- microsoft-extensions-hosting
microsoft-extensions-logging-debug <- microsoft-extensions-hosting
microsoft-extensions-logging-eventlog <- microsoft-extensions-hosting
microsoft-extensions-logging-eventsource <- microsoft-extensions-hosting
microsoft-extensions-logging <- microsoft-extensions-hosting
microsoft-extensions-options <- microsoft-extensions-hosting
system-diagnostics-diagnosticsource <- microsoft-extensions-hosting
aoi.alloverit <- aoi.alloverit-validation
fluentvalidation <- aoi.alloverit-validation
aoi.alloverit-reactive <- aoi.alloverit-aws-appsync-client
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-aws-appsync-client
microsoft-extensions-dependencyinjection <- aoi.alloverit-aws-appsync-client
microsoft-extensions-dependencyinjection-abstractions <- microsoft-extensions-dependencyinjection
microsoft-extensions-http <- aoi.alloverit-aws-appsync-client
microsoft-extensions-dependencyinjection-abstractions <- microsoft-extensions-http
microsoft-extensions-logging-abstractions <- microsoft-extensions-http
microsoft-extensions-logging <- microsoft-extensions-http
microsoft-extensions-options <- microsoft-extensions-http
aoi.alloverit <- aoi.alloverit-aspnetcore
microsoft-aspnetcore-mvc <- aoi.alloverit-aspnetcore
microsoft-aspnetcore-mvc-analyzers <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-apiexplorer <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-cors <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-dataannotations <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-formatters-json <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-localization <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-razorpages <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-taghelpers <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-viewfeatures <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-mvc-razor-extensions <- microsoft-aspnetcore-mvc
microsoft-aspnetcore-razor-design <- microsoft-aspnetcore-mvc
microsoft-extensions-caching-memory <- microsoft-aspnetcore-mvc
microsoft-extensions-dependencyinjection <- microsoft-aspnetcore-mvc
aoi.alloverit <- aoi.alloverit-entityframeworkcore
microsoft-entityframeworkcore-relational <- aoi.alloverit-entityframeworkcore
microsoft-entityframeworkcore <- microsoft-entityframeworkcore-relational
microsoft-extensions-configuration-abstractions <- microsoft-entityframeworkcore-relational
aoi.alloverit <- aoi.alloverit-csv
csvhelper <- aoi.alloverit-csv
microsoft-csharp <- csvhelper
aoi.alloverit <- aoi.alloverit-reactive
system-reactive <- aoi.alloverit-reactive
system-threading-tasks-extensions <- system-reactive
aoi.alloverit <- aoi.alloverit-dependencyinjection
microsoft-extensions-dependencyinjection-abstractions <- aoi.alloverit-dependencyinjection
aoi.alloverit-serialization-binary <- aoi.alloverit-pagination
microsoft-extensions-dependencyinjection-abstractions <- aoi.alloverit-pagination
aoi.alloverit-entityframeworkcore <- aoi.alloverit-entityframeworkcore-pagination
aoi.alloverit-pagination <- aoi.alloverit-entityframeworkcore-pagination
aoi.alloverit <- aoi.alloverit-reactiveui
microsoft-extensions-dependencyinjection-abstractions <- aoi.alloverit-reactiveui
reactiveui <- aoi.alloverit-reactiveui
dynamicdata <- reactiveui
splat <- reactiveui
system-componentmodel <- reactiveui
system-diagnostics-contracts <- reactiveui
system-dynamic-runtime <- reactiveui
system-runtime-serialization-primitives <- reactiveui
reactiveui-fody <- aoi.alloverit-reactiveui
reactiveui <- reactiveui-fody
fody <- reactiveui-fody
system-componentmodel <- reactiveui-fody
system-diagnostics-contracts <- reactiveui-fody
system-dynamic-runtime <- reactiveui-fody
system-runtime-serialization-primitives <- reactiveui-fody
aoi.alloverit <- aoi.alloverit-filtering
aoi.alloverit-validation <- aoi.alloverit-validation-options
microsoft-extensions-options <- aoi.alloverit-validation-options
microsoft-extensions-dependencyinjection-abstractions <- microsoft-extensions-options
microsoft-extensions-primitives <- microsoft-extensions-options
aoi.alloverit <- aoi.alloverit-entityframeworkcore-diagrams
microsoft-entityframeworkcore-relational <- aoi.alloverit-entityframeworkcore-diagrams
aoi.alloverit <- aoi.alloverit-mapping
aoi.alloverit <- aoi.alloverit-serialization-binary
aoi.alloverit <- aoi.alloverit-serialization-json-abstractions
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-serialization-json-newtonsoft
newtonsoft-json <- aoi.alloverit-serialization-json-newtonsoft
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-serialization-json-systemtext
system-text-json <- aoi.alloverit-serialization-json-systemtext
microsoft-bcl-asyncinterfaces <- system-text-json
system-text-encodings-web <- system-text-json
system-buffers <- system-text-json
system-memory <- system-text-json
system-numerics-vectors <- system-text-json
system-runtime-compilerservices-unsafe <- system-text-json
system-threading-tasks-extensions <- system-text-json
aoi.alloverit <- aoi.alloverit-wpf
aoi.alloverit <- aoi.alloverit-wpf-controls
