direction: right

aoi: AllOverIt
aoi.alloverit-fixture: AllOverIt.Fixture
autofixture: AutoFixture
autofixture.style.fill: lightblue
autofixture.style.opacity: 0.8
fluentassertions: FluentAssertions
fluentassertions.style.fill: lightblue
fluentassertions.style.opacity: 0.8

autofixture <- aoi.alloverit-fixture
fluentassertions <- aoi.alloverit-fixture
