direction: right

aoi: AllOverIt
aoi.alloverit-aws-cdk-appsync: AllOverIt.Aws.Cdk.AppSync
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
amazon-cdk-aws-appsync: Amazon.CDK.AWS.AppSync
amazon-cdk-aws-appsync.style.fill: lightblue
amazon-cdk-aws-appsync.style.opacity: 0.8
amazon-cdk-aws-certificatemanager: Amazon.CDK.AWS.CertificateManager
amazon-cdk-aws-certificatemanager.style.fill: lightblue
amazon-cdk-aws-certificatemanager.style.opacity: 0.8
amazon-cdk-aws-cognito: Amazon.CDK.AWS.Cognito
amazon-cdk-aws-cognito.style.fill: lightblue
amazon-cdk-aws-cognito.style.opacity: 0.8
amazon-cdk-aws-dynamodb: Amazon.CDK.AWS.DynamoDB
amazon-cdk-aws-dynamodb.style.fill: lightblue
amazon-cdk-aws-dynamodb.style.opacity: 0.8
amazon-cdk-aws-ec2: Amazon.CDK.AWS.EC2
amazon-cdk-aws-ec2.style.fill: lightblue
amazon-cdk-aws-ec2.style.opacity: 0.8
amazon-cdk-aws-elasticsearch: Amazon.CDK.AWS.Elasticsearch
amazon-cdk-aws-elasticsearch.style.fill: lightblue
amazon-cdk-aws-elasticsearch.style.opacity: 0.8
amazon-cdk-aws-iam: Amazon.CDK.AWS.IAM
amazon-cdk-aws-iam.style.fill: lightblue
amazon-cdk-aws-iam.style.opacity: 0.8
amazon-cdk-aws-lambda: Amazon.CDK.AWS.Lambda
amazon-cdk-aws-lambda.style.fill: lightblue
amazon-cdk-aws-lambda.style.opacity: 0.8
amazon-cdk-aws-opensearchservice: Amazon.CDK.AWS.OpenSearchService
amazon-cdk-aws-opensearchservice.style.fill: lightblue
amazon-cdk-aws-opensearchservice.style.opacity: 0.8
amazon-cdk-aws-rds: Amazon.CDK.AWS.RDS
amazon-cdk-aws-rds.style.fill: lightblue
amazon-cdk-aws-rds.style.opacity: 0.8
amazon-cdk-aws-s3-assets: Amazon.CDK.AWS.S3.Assets
amazon-cdk-aws-s3-assets.style.fill: lightblue
amazon-cdk-aws-s3-assets.style.opacity: 0.8
amazon-cdk-aws-secretsmanager: Amazon.CDK.AWS.SecretsManager
amazon-cdk-aws-secretsmanager.style.fill: lightblue
amazon-cdk-aws-secretsmanager.style.opacity: 0.8
amazon-cdk: Amazon.CDK
amazon-cdk.style.fill: lightblue
amazon-cdk.style.opacity: 0.8
amazon-jsii-runtime: Amazon.JSII.Runtime
amazon-jsii-runtime.style.fill: lightblue
amazon-jsii-runtime.style.opacity: 0.8
constructs: Constructs
constructs.style.fill: lightblue
constructs.style.opacity: 0.8

aoi.alloverit <- aoi.alloverit-aws-cdk-appsync
aoi.alloverit-assertion <- aoi.alloverit
amazon-cdk-aws-appsync <- aoi.alloverit-aws-cdk-appsync
amazon-cdk-aws-certificatemanager <- amazon-cdk-aws-appsync
amazon-cdk-aws-cognito <- amazon-cdk-aws-appsync
amazon-cdk-aws-dynamodb <- amazon-cdk-aws-appsync
amazon-cdk-aws-ec2 <- amazon-cdk-aws-appsync
amazon-cdk-aws-elasticsearch <- amazon-cdk-aws-appsync
amazon-cdk-aws-iam <- amazon-cdk-aws-appsync
amazon-cdk-aws-lambda <- amazon-cdk-aws-appsync
amazon-cdk-aws-opensearchservice <- amazon-cdk-aws-appsync
amazon-cdk-aws-rds <- amazon-cdk-aws-appsync
amazon-cdk-aws-s3-assets <- amazon-cdk-aws-appsync
amazon-cdk-aws-secretsmanager <- amazon-cdk-aws-appsync
amazon-cdk <- amazon-cdk-aws-appsync
amazon-jsii-runtime <- amazon-cdk-aws-appsync
constructs <- amazon-cdk-aws-appsync
