direction: right

aoi: AllOverIt
aoi.alloverit-pagination: AllOverIt.Pagination
microsoft-extensions-dependencyinjection-abstractions_7-0-0: Microsoft.Extensions.DependencyInjection.Abstractions\nv7.0.0
microsoft-extensions-dependencyinjection-abstractions_7-0-0.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions_7-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_7-0-0 <- aoi.alloverit-pagination
aoi.alloverit-serialization-binary: AllOverIt.Serialization.Binary
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-serialization-binary
aoi.alloverit-serialization-binary <- aoi.alloverit-pagination
