direction: right

aoi: AllOverIt
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit-aspnetcore: AllOverIt.AspNetCore
microsoft-aspnetcore-mvc_2-2-0: Microsoft.AspNetCore.Mvc\nv2.2.0
microsoft-aspnetcore-mvc_2-2-0.style.fill: "#ADD8E6"
microsoft-aspnetcore-mvc_2-2-0.style.opacity: 0.8
microsoft-aspnetcore-mvc_2-2-0 <- aoi.alloverit-aspnetcore
aoi.alloverit <- aoi.alloverit-aspnetcore
aoi.alloverit-aws-appsync-client: AllOverIt.Aws.AppSync.Client
microsoft-extensions-dependencyinjection_7-0-0: Microsoft.Extensions.DependencyInjection\nv7.0.0
microsoft-extensions-dependencyinjection_7-0-0.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection_7-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection_7-0-0 <- aoi.alloverit-aws-appsync-client
microsoft-extensions-http_7-0-0: Microsoft.Extensions.Http\nv7.0.0
microsoft-extensions-http_7-0-0.style.fill: "#ADD8E6"
microsoft-extensions-http_7-0-0.style.opacity: 0.8
microsoft-extensions-http_7-0-0 <- aoi.alloverit-aws-appsync-client
aoi.alloverit-reactive: AllOverIt.Reactive
system-reactive_6-0-0: System.Reactive\nv6.0.0
system-reactive_6-0-0.style.fill: "#ADD8E6"
system-reactive_6-0-0.style.opacity: 0.8
system-reactive_6-0-0 <- aoi.alloverit-reactive
aoi.alloverit <- aoi.alloverit-reactive
aoi.alloverit-reactive <- aoi.alloverit-aws-appsync-client
aoi.alloverit-serialization-json-abstractions: AllOverIt.Serialization.Json.Abstractions
aoi.alloverit <- aoi.alloverit-serialization-json-abstractions
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-aws-appsync-client
aoi.alloverit-aws-cdk-appsync: AllOverIt.Aws.Cdk.AppSync
amazon-cdk-aws-appsync_1-204-0: Amazon.CDK.AWS.AppSync\nv1.204.0
amazon-cdk-aws-appsync_1-204-0.style.fill: "#ADD8E6"
amazon-cdk-aws-appsync_1-204-0.style.opacity: 0.8
amazon-cdk-aws-appsync_1-204-0 <- aoi.alloverit-aws-cdk-appsync
aoi.alloverit <- aoi.alloverit-aws-cdk-appsync
aoi.alloverit-csv: AllOverIt.Csv
csvhelper_30-0-1: CsvHelper\nv30.0.1
csvhelper_30-0-1.style.fill: "#ADD8E6"
csvhelper_30-0-1.style.opacity: 0.8
csvhelper_30-0-1 <- aoi.alloverit-csv
aoi.alloverit <- aoi.alloverit-csv
aoi.alloverit-dependencyinjection: AllOverIt.DependencyInjection
microsoft-extensions-dependencyinjection-abstractions_7-0-0: Microsoft.Extensions.DependencyInjection.Abstractions\nv7.0.0
microsoft-extensions-dependencyinjection-abstractions_7-0-0.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions_7-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_7-0-0 <- aoi.alloverit-dependencyinjection
aoi.alloverit <- aoi.alloverit-dependencyinjection
aoi.alloverit-entityframeworkcore: AllOverIt.EntityFrameworkCore
microsoft-entityframeworkcore-relational_7-0-8: Microsoft.EntityFrameworkCore.Relational\nv7.0.8
microsoft-entityframeworkcore-relational_7-0-8.style.fill: "#ADD8E6"
microsoft-entityframeworkcore-relational_7-0-8.style.opacity: 0.8
microsoft-entityframeworkcore-relational_7-0-8 <- aoi.alloverit-entityframeworkcore
aoi.alloverit <- aoi.alloverit-entityframeworkcore
aoi.alloverit-entityframeworkcore-diagrams: AllOverIt.EntityFrameworkCore.Diagrams
microsoft-entityframeworkcore-relational_7-0-8 <- aoi.alloverit-entityframeworkcore-diagrams
aoi.alloverit <- aoi.alloverit-entityframeworkcore-diagrams
aoi.alloverit-entityframeworkcore-pagination: AllOverIt.EntityFrameworkCore.Pagination
aoi.alloverit-entityframeworkcore <- aoi.alloverit-entityframeworkcore-pagination
aoi.alloverit-pagination: AllOverIt.Pagination
microsoft-extensions-dependencyinjection-abstractions_7-0-0 <- aoi.alloverit-pagination
aoi.alloverit-serialization-binary: AllOverIt.Serialization.Binary
aoi.alloverit <- aoi.alloverit-serialization-binary
aoi.alloverit-serialization-binary <- aoi.alloverit-pagination
aoi.alloverit-pagination <- aoi.alloverit-entityframeworkcore-pagination
aoi.alloverit-evaluator: AllOverIt.Evaluator
aoi.alloverit <- aoi.alloverit-evaluator
aoi.alloverit-filtering: AllOverIt.Filtering
aoi.alloverit <- aoi.alloverit-filtering
aoi.alloverit-fixture: AllOverIt.Fixture
autofixture_4-18-0: AutoFixture\nv4.18.0
autofixture_4-18-0.style.fill: "#ADD8E6"
autofixture_4-18-0.style.opacity: 0.8
autofixture_4-18-0 <- aoi.alloverit-fixture
fluentassertions_6-11-0: FluentAssertions\nv6.11.0
fluentassertions_6-11-0.style.fill: "#ADD8E6"
fluentassertions_6-11-0.style.opacity: 0.8
fluentassertions_6-11-0 <- aoi.alloverit-fixture
aoi.alloverit-fixture-fakeiteasy: AllOverIt.Fixture.FakeItEasy
autofixture-autofakeiteasy_4-18-0: AutoFixture.AutoFakeItEasy\nv4.18.0
autofixture-autofakeiteasy_4-18-0.style.fill: "#ADD8E6"
autofixture-autofakeiteasy_4-18-0.style.opacity: 0.8
autofixture-autofakeiteasy_4-18-0 <- aoi.alloverit-fixture-fakeiteasy
fakeiteasy_7-4-0: FakeItEasy\nv7.4.0
fakeiteasy_7-4-0.style.fill: "#ADD8E6"
fakeiteasy_7-4-0.style.opacity: 0.8
fakeiteasy_7-4-0 <- aoi.alloverit-fixture-fakeiteasy
aoi.alloverit-fixture <- aoi.alloverit-fixture-fakeiteasy
aoi.alloverit-generichost: AllOverIt.GenericHost
microsoft-extensions-hosting_7-0-1: Microsoft.Extensions.Hosting\nv7.0.1
microsoft-extensions-hosting_7-0-1.style.fill: "#ADD8E6"
microsoft-extensions-hosting_7-0-1.style.opacity: 0.8
microsoft-extensions-hosting_7-0-1 <- aoi.alloverit-generichost
aoi.alloverit <- aoi.alloverit-generichost
aoi.alloverit-mapping: AllOverIt.Mapping
aoi.alloverit <- aoi.alloverit-mapping
aoi.alloverit-pipes: AllOverIt.Pipes
aoi.alloverit-serialization-binary <- aoi.alloverit-pipes
aoi.alloverit-reactive <- aoi.alloverit-pipes
aoi.alloverit-reactiveui: AllOverIt.ReactiveUI
microsoft-extensions-dependencyinjection-abstractions_7-0-0 <- aoi.alloverit-reactiveui
reactiveui_19-2-1: ReactiveUI\nv19.2.1
reactiveui_19-2-1.style.fill: "#ADD8E6"
reactiveui_19-2-1.style.opacity: 0.8
reactiveui_19-2-1 <- aoi.alloverit-reactiveui
aoi.alloverit <- aoi.alloverit-reactiveui
aoi.alloverit-serialization-json-newtonsoft: AllOverIt.Serialization.Json.Newtonsoft
newtonsoft-json_13-0-3: Newtonsoft.Json\nv13.0.3
newtonsoft-json_13-0-3.style.fill: "#ADD8E6"
newtonsoft-json_13-0-3.style.opacity: 0.8
newtonsoft-json_13-0-3 <- aoi.alloverit-serialization-json-newtonsoft
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-serialization-json-newtonsoft
aoi.alloverit-serialization-json-systemtext: AllOverIt.Serialization.Json.SystemText
system-text-json_7-0-3: System.Text.Json\nv7.0.3
system-text-json_7-0-3.style.fill: "#ADD8E6"
system-text-json_7-0-3.style.opacity: 0.8
system-text-json_7-0-3 <- aoi.alloverit-serialization-json-systemtext
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-serialization-json-systemtext
aoi.alloverit-validation: AllOverIt.Validation
fluentvalidation_11-5-2: FluentValidation\nv11.5.2
fluentvalidation_11-5-2.style.fill: "#ADD8E6"
fluentvalidation_11-5-2.style.opacity: 0.8
fluentvalidation_11-5-2 <- aoi.alloverit-validation
aoi.alloverit <- aoi.alloverit-validation
aoi.alloverit-validation-options: AllOverIt.Validation.Options
microsoft-extensions-options_7-0-1: Microsoft.Extensions.Options\nv7.0.1
microsoft-extensions-options_7-0-1.style.fill: "#ADD8E6"
microsoft-extensions-options_7-0-1.style.opacity: 0.8
microsoft-extensions-options_7-0-1 <- aoi.alloverit-validation-options
aoi.alloverit-validation <- aoi.alloverit-validation-options
aoi.alloverit-wpf: AllOverIt.Wpf
aoi.alloverit <- aoi.alloverit-wpf
aoi.alloverit-wpf-controls: AllOverIt.Wpf.Controls
microsoft-xaml-behaviors-wpf_1-1-39: Microsoft.Xaml.Behaviors.Wpf\nv1.1.39
microsoft-xaml-behaviors-wpf_1-1-39.style.fill: "#ADD8E6"
microsoft-xaml-behaviors-wpf_1-1-39.style.opacity: 0.8
microsoft-xaml-behaviors-wpf_1-1-39 <- aoi.alloverit-wpf-controls
aoi.alloverit <- aoi.alloverit-wpf-controls
