direction: right

aoi: AllOverIt
aoi.alloverit-wpf: AllOverIt.Wpf
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion

aoi.alloverit <- aoi.alloverit-wpf
aoi.alloverit-assertion <- aoi.alloverit
