direction: right

aoi: AllOverIt
aoi.alloverit-validation: AllOverIt.Validation
aoi.alloverit: AllOverIt
fluentvalidation: FluentValidation
fluentvalidation.style.fill: lightblue
fluentvalidation.style.opacity: 0.8

aoi.alloverit <- aoi.alloverit-validation
fluentvalidation <- aoi.alloverit-validation
