direction: right

aoi: AllOverIt
aoi.alloverit-entityframeworkcore-diagrams: AllOverIt.EntityFrameworkCore.Diagrams
microsoft-entityframeworkcore-relational_7-0-5: Microsoft.EntityFrameworkCore.Relational\nv7.0.5
microsoft-entityframeworkcore-relational_7-0-5.style.fill: "#ADD8E6"
microsoft-entityframeworkcore-relational_7-0-5.style.opacity: 0.8
microsoft-entityframeworkcore_7-0-5: Microsoft.EntityFrameworkCore\nv7.0.5
microsoft-entityframeworkcore_7-0-5.style.fill: "#FFEC96"
microsoft-entityframeworkcore_7-0-5.style.opacity: 0.8
microsoft-entityframeworkcore_7-0-5 <- microsoft-entityframeworkcore-relational_7-0-5
microsoft-extensions-configuration-abstractions_7-0-0: Microsoft.Extensions.Configuration.Abstractions\nv7.0.0
microsoft-extensions-configuration-abstractions_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-abstractions_7-0-0.style.opacity: 0.8
microsoft-extensions-configuration-abstractions_7-0-0 <- microsoft-entityframeworkcore-relational_7-0-5
microsoft-entityframeworkcore-relational_7-0-5 <- aoi.alloverit-entityframeworkcore-diagrams
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-entityframeworkcore-diagrams
