direction: right

aoi: AllOverIt
aoi.alloverit-pagination: AllOverIt.Pagination
aoi.alloverit-serialization-binary: AllOverIt.Serialization.Binary
microsoft-extensions-dependencyinjection-abstractions: Microsoft.Extensions.DependencyInjection.Abstractions
microsoft-extensions-dependencyinjection-abstractions.style.fill: lightblue
microsoft-extensions-dependencyinjection-abstractions.style.opacity: 0.8

aoi.alloverit-serialization-binary <- aoi.alloverit-pagination
microsoft-extensions-dependencyinjection-abstractions <- aoi.alloverit-pagination
