direction: right

aoi: AllOverIt
aoi.alloverit-serialization-json-newtonsoft: AllOverIt.Serialization.Json.Newtonsoft
newtonsoft-json: Newtonsoft.Json
newtonsoft-json.style.fill: "#ADD8E6"
newtonsoft-json.style.opacity: 0.8
newtonsoft-json <- aoi.alloverit-serialization-json-newtonsoft
aoi.alloverit-serialization-json-abstractions: AllOverIt.Serialization.Json.Abstractions
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-serialization-json-abstractions
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-serialization-json-newtonsoft
