direction: right

aoi: AllOverIt
aoi.alloverit-filtering: AllOverIt.Filtering
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion

aoi.alloverit <- aoi.alloverit-filtering
aoi.alloverit-assertion <- aoi.alloverit
