direction: right

aoi: AllOverIt
aoi.alloverit-aws-appsync-client: AllOverIt.Aws.AppSync.Client
microsoft-extensions-dependencyinjection_7-0-0: Microsoft.Extensions.DependencyInjection\nv7.0.0
microsoft-extensions-dependencyinjection_7-0-0.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection_7-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_7-0-0: Microsoft.Extensions.DependencyInjection.Abstractions\nv7.0.0
microsoft-extensions-dependencyinjection-abstractions_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection-abstractions_7-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_7-0-0 <- microsoft-extensions-dependencyinjection_7-0-0
microsoft-extensions-dependencyinjection_7-0-0 <- aoi.alloverit-aws-appsync-client
microsoft-extensions-http_7-0-0: Microsoft.Extensions.Http\nv7.0.0
microsoft-extensions-http_7-0-0.style.fill: "#ADD8E6"
microsoft-extensions-http_7-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_7-0-0 <- microsoft-extensions-http_7-0-0
microsoft-extensions-logging-abstractions_7-0-0: Microsoft.Extensions.Logging.Abstractions\nv7.0.0
microsoft-extensions-logging-abstractions_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-abstractions_7-0-0.style.opacity: 0.8
microsoft-extensions-logging-abstractions_7-0-0 <- microsoft-extensions-http_7-0-0
microsoft-extensions-logging_7-0-0: Microsoft.Extensions.Logging\nv7.0.0
microsoft-extensions-logging_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging_7-0-0.style.opacity: 0.8
microsoft-extensions-logging_7-0-0 <- microsoft-extensions-http_7-0-0
microsoft-extensions-options_7-0-0: Microsoft.Extensions.Options\nv7.0.0
microsoft-extensions-options_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-options_7-0-0.style.opacity: 0.8
microsoft-extensions-options_7-0-0 <- microsoft-extensions-http_7-0-0
microsoft-extensions-http_7-0-0 <- aoi.alloverit-aws-appsync-client
aoi.alloverit-reactive: AllOverIt.Reactive
system-reactive_5-0-0: System.Reactive\nv5.0.0
system-reactive_5-0-0.style.fill: "#ADD8E6"
system-reactive_5-0-0.style.opacity: 0.8
system-threading-tasks-extensions_4-5-4: System.Threading.Tasks.Extensions\nv4.5.4
system-threading-tasks-extensions_4-5-4.style.fill: "#FFEC96"
system-threading-tasks-extensions_4-5-4.style.opacity: 0.8
system-threading-tasks-extensions_4-5-4 <- system-reactive_5-0-0
system-reactive_5-0-0 <- aoi.alloverit-reactive
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-reactive
aoi.alloverit-reactive <- aoi.alloverit-aws-appsync-client
aoi.alloverit-serialization-json-abstractions: AllOverIt.Serialization.Json.Abstractions
aoi.alloverit <- aoi.alloverit-serialization-json-abstractions
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-aws-appsync-client
