direction: right

aoi: AllOverIt
aoi.alloverit-reactive: AllOverIt.Reactive
aoi.alloverit: AllOverIt
system-reactive: System.Reactive
system-reactive.style.fill: lightblue
system-reactive.style.opacity: 0.8

aoi.alloverit <- aoi.alloverit-reactive
system-reactive <- aoi.alloverit-reactive
