direction: right

aoi: AllOverIt
aoi.alloverit-serialization-json-systemtext: AllOverIt.Serialization.Json.SystemText
system-text-json: System.Text.Json
system-text-json.style.fill: "#ADD8E6"
system-text-json.style.opacity: 0.8
microsoft-bcl-asyncinterfaces: Microsoft.Bcl.AsyncInterfaces
microsoft-bcl-asyncinterfaces.style.fill: "#FFEC96"
microsoft-bcl-asyncinterfaces.style.opacity: 0.8
microsoft-bcl-asyncinterfaces <- system-text-json
system-text-encodings-web: System.Text.Encodings.Web
system-text-encodings-web.style.fill: "#FFEC96"
system-text-encodings-web.style.opacity: 0.8
system-text-encodings-web <- system-text-json
system-buffers: System.Buffers
system-buffers.style.fill: "#FFEC96"
system-buffers.style.opacity: 0.8
system-buffers <- system-text-json
system-memory: System.Memory
system-memory.style.fill: "#FFEC96"
system-memory.style.opacity: 0.8
system-memory <- system-text-json
system-numerics-vectors: System.Numerics.Vectors
system-numerics-vectors.style.fill: "#FFEC96"
system-numerics-vectors.style.opacity: 0.8
system-numerics-vectors <- system-text-json
system-runtime-compilerservices-unsafe: System.Runtime.CompilerServices.Unsafe
system-runtime-compilerservices-unsafe.style.fill: "#FFEC96"
system-runtime-compilerservices-unsafe.style.opacity: 0.8
system-runtime-compilerservices-unsafe <- system-text-json
system-threading-tasks-extensions: System.Threading.Tasks.Extensions
system-threading-tasks-extensions.style.fill: "#FFEC96"
system-threading-tasks-extensions.style.opacity: 0.8
system-threading-tasks-extensions <- system-text-json
system-text-json <- aoi.alloverit-serialization-json-systemtext
aoi.alloverit-serialization-json-abstractions: AllOverIt.Serialization.Json.Abstractions
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-serialization-json-abstractions
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-serialization-json-systemtext
