direction: right

aoi: AllOverIt
aoi.alloverit-reactiveui: AllOverIt.ReactiveUI
microsoft-extensions-dependencyinjection-abstractions_7-0-0: Microsoft.Extensions.DependencyInjection.Abstractions\nv7.0.0
microsoft-extensions-dependencyinjection-abstractions_7-0-0.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions_7-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_7-0-0 <- aoi.alloverit-reactiveui
reactiveui_18-4-44: ReactiveUI\nv18.4.44
reactiveui_18-4-44.style.fill: "#ADD8E6"
reactiveui_18-4-44.style.opacity: 0.8
dynamicdata_7-13-5: DynamicData\nv7.13.5
dynamicdata_7-13-5.style.fill: "#FFEC96"
dynamicdata_7-13-5.style.opacity: 0.8
dynamicdata_7-13-5 <- reactiveui_18-4-44
splat_14-6-8: Splat\nv14.6.8
splat_14-6-8.style.fill: "#FFEC96"
splat_14-6-8.style.opacity: 0.8
splat_14-6-8 <- reactiveui_18-4-44
reactiveui_18-4-44 <- aoi.alloverit-reactiveui
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-reactiveui
