direction: right

aoi: AllOverIt
aoi.alloverit-generichost: AllOverIt.GenericHost
microsoft-extensions-hosting_7-0-1: Microsoft.Extensions.Hosting\nv7.0.1
microsoft-extensions-hosting_7-0-1.style.fill: "#ADD8E6"
microsoft-extensions-hosting_7-0-1.style.opacity: 0.8
microsoft-extensions-configuration-abstractions_7-0-0: Microsoft.Extensions.Configuration.Abstractions\nv7.0.0
microsoft-extensions-configuration-abstractions_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-abstractions_7-0-0.style.opacity: 0.8
microsoft-extensions-configuration-abstractions_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-configuration-binder_7-0-3: Microsoft.Extensions.Configuration.Binder\nv7.0.3
microsoft-extensions-configuration-binder_7-0-3.style.fill: "#FFEC96"
microsoft-extensions-configuration-binder_7-0-3.style.opacity: 0.8
microsoft-extensions-configuration-binder_7-0-3 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-configuration-commandline_7-0-0: Microsoft.Extensions.Configuration.CommandLine\nv7.0.0
microsoft-extensions-configuration-commandline_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-commandline_7-0-0.style.opacity: 0.8
microsoft-extensions-configuration-commandline_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-configuration-environmentvariables_7-0-0: Microsoft.Extensions.Configuration.EnvironmentVariables\nv7.0.0
microsoft-extensions-configuration-environmentvariables_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-environmentvariables_7-0-0.style.opacity: 0.8
microsoft-extensions-configuration-environmentvariables_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-configuration-fileextensions_7-0-0: Microsoft.Extensions.Configuration.FileExtensions\nv7.0.0
microsoft-extensions-configuration-fileextensions_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-fileextensions_7-0-0.style.opacity: 0.8
microsoft-extensions-configuration-fileextensions_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-configuration-json_7-0-0: Microsoft.Extensions.Configuration.Json\nv7.0.0
microsoft-extensions-configuration-json_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-json_7-0-0.style.opacity: 0.8
microsoft-extensions-configuration-json_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-configuration-usersecrets_7-0-0: Microsoft.Extensions.Configuration.UserSecrets\nv7.0.0
microsoft-extensions-configuration-usersecrets_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration-usersecrets_7-0-0.style.opacity: 0.8
microsoft-extensions-configuration-usersecrets_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-configuration_7-0-0: Microsoft.Extensions.Configuration\nv7.0.0
microsoft-extensions-configuration_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-configuration_7-0-0.style.opacity: 0.8
microsoft-extensions-configuration_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-dependencyinjection-abstractions_7-0-0: Microsoft.Extensions.DependencyInjection.Abstractions\nv7.0.0
microsoft-extensions-dependencyinjection-abstractions_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection-abstractions_7-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-dependencyinjection_7-0-0: Microsoft.Extensions.DependencyInjection\nv7.0.0
microsoft-extensions-dependencyinjection_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection_7-0-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-fileproviders-abstractions_7-0-0: Microsoft.Extensions.FileProviders.Abstractions\nv7.0.0
microsoft-extensions-fileproviders-abstractions_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-fileproviders-abstractions_7-0-0.style.opacity: 0.8
microsoft-extensions-fileproviders-abstractions_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-fileproviders-physical_7-0-0: Microsoft.Extensions.FileProviders.Physical\nv7.0.0
microsoft-extensions-fileproviders-physical_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-fileproviders-physical_7-0-0.style.opacity: 0.8
microsoft-extensions-fileproviders-physical_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-hosting-abstractions_7-0-0: Microsoft.Extensions.Hosting.Abstractions\nv7.0.0
microsoft-extensions-hosting-abstractions_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-hosting-abstractions_7-0-0.style.opacity: 0.8
microsoft-extensions-hosting-abstractions_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-logging-abstractions_7-0-0: Microsoft.Extensions.Logging.Abstractions\nv7.0.0
microsoft-extensions-logging-abstractions_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-abstractions_7-0-0.style.opacity: 0.8
microsoft-extensions-logging-abstractions_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-logging-configuration_7-0-0: Microsoft.Extensions.Logging.Configuration\nv7.0.0
microsoft-extensions-logging-configuration_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-configuration_7-0-0.style.opacity: 0.8
microsoft-extensions-logging-configuration_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-logging-console_7-0-0: Microsoft.Extensions.Logging.Console\nv7.0.0
microsoft-extensions-logging-console_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-console_7-0-0.style.opacity: 0.8
microsoft-extensions-logging-console_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-logging-debug_7-0-0: Microsoft.Extensions.Logging.Debug\nv7.0.0
microsoft-extensions-logging-debug_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-debug_7-0-0.style.opacity: 0.8
microsoft-extensions-logging-debug_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-logging-eventlog_7-0-0: Microsoft.Extensions.Logging.EventLog\nv7.0.0
microsoft-extensions-logging-eventlog_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-eventlog_7-0-0.style.opacity: 0.8
microsoft-extensions-logging-eventlog_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-logging-eventsource_7-0-0: Microsoft.Extensions.Logging.EventSource\nv7.0.0
microsoft-extensions-logging-eventsource_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging-eventsource_7-0-0.style.opacity: 0.8
microsoft-extensions-logging-eventsource_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-logging_7-0-0: Microsoft.Extensions.Logging\nv7.0.0
microsoft-extensions-logging_7-0-0.style.fill: "#FFEC96"
microsoft-extensions-logging_7-0-0.style.opacity: 0.8
microsoft-extensions-logging_7-0-0 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-options_7-0-1: Microsoft.Extensions.Options\nv7.0.1
microsoft-extensions-options_7-0-1.style.fill: "#FFEC96"
microsoft-extensions-options_7-0-1.style.opacity: 0.8
microsoft-extensions-options_7-0-1 <- microsoft-extensions-hosting_7-0-1
system-diagnostics-diagnosticsource_7-0-1: System.Diagnostics.DiagnosticSource\nv7.0.1
system-diagnostics-diagnosticsource_7-0-1.style.fill: "#FFEC96"
system-diagnostics-diagnosticsource_7-0-1.style.opacity: 0.8
system-diagnostics-diagnosticsource_7-0-1 <- microsoft-extensions-hosting_7-0-1
microsoft-extensions-hosting_7-0-1 <- aoi.alloverit-generichost
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-generichost
