direction: right

aoi: AllOverIt
aoi.alloverit-entityframeworkcore-diagrams: AllOverIt.EntityFrameworkCore.Diagrams
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
microsoft-entityframeworkcore-relational: Microsoft.EntityFrameworkCore.Relational
microsoft-entityframeworkcore-relational.style.fill: lightblue
microsoft-entityframeworkcore-relational.style.opacity: 0.8

aoi.alloverit <- aoi.alloverit-entityframeworkcore-diagrams
aoi.alloverit-assertion <- aoi.alloverit
microsoft-entityframeworkcore-relational <- aoi.alloverit-entityframeworkcore-diagrams
