direction: right

aoi: AllOverIt
aoi.alloverit-aws-cdk-appsync: AllOverIt.Aws.Cdk.AppSync
amazon-cdk-lib_2-87-0: Amazon.CDK.Lib\nv2.87.0
amazon-cdk-lib_2-87-0.style.fill: "#ADD8E6"
amazon-cdk-lib_2-87-0.style.opacity: 0.8
amazon-cdk-asset-awscliv1_2-2-177: Amazon.CDK.Asset.AwsCliV1\nv2.2.177
amazon-cdk-asset-awscliv1_2-2-177.style.fill: "#FFEC96"
amazon-cdk-asset-awscliv1_2-2-177.style.opacity: 0.8
amazon-cdk-asset-awscliv1_2-2-177 <- amazon-cdk-lib_2-87-0
amazon-cdk-asset-kubectlv20_2-1-1: Amazon.CDK.Asset.KubectlV20\nv2.1.1
amazon-cdk-asset-kubectlv20_2-1-1.style.fill: "#FFEC96"
amazon-cdk-asset-kubectlv20_2-1-1.style.opacity: 0.8
amazon-cdk-asset-kubectlv20_2-1-1 <- amazon-cdk-lib_2-87-0
amazon-cdk-asset-nodeproxyagentv5_2-0-148: Amazon.CDK.Asset.NodeProxyAgentV5\nv2.0.148
amazon-cdk-asset-nodeproxyagentv5_2-0-148.style.fill: "#FFEC96"
amazon-cdk-asset-nodeproxyagentv5_2-0-148.style.opacity: 0.8
amazon-cdk-asset-nodeproxyagentv5_2-0-148 <- amazon-cdk-lib_2-87-0
amazon-jsii-runtime_1-82-0: Amazon.JSII.Runtime\nv1.82.0
amazon-jsii-runtime_1-82-0.style.fill: "#FFEC96"
amazon-jsii-runtime_1-82-0.style.opacity: 0.8
amazon-jsii-runtime_1-82-0 <- amazon-cdk-lib_2-87-0
constructs_10-0-0: Constructs\nv10.0.0
constructs_10-0-0.style.fill: "#FFEC96"
constructs_10-0-0.style.opacity: 0.8
constructs_10-0-0 <- amazon-cdk-lib_2-87-0
amazon-cdk-lib_2-87-0 <- aoi.alloverit-aws-cdk-appsync
cdklabs-awscdkappsyncutils_0-0-152: Cdklabs.AwsCdkAppsyncUtils\nv0.0.152
cdklabs-awscdkappsyncutils_0-0-152.style.fill: "#ADD8E6"
cdklabs-awscdkappsyncutils_0-0-152.style.opacity: 0.8
amazon-cdk-lib_2-60-0: Amazon.CDK.Lib\nv2.60.0
amazon-cdk-lib_2-60-0.style.fill: "#FFEC96"
amazon-cdk-lib_2-60-0.style.opacity: 0.8
amazon-cdk-lib_2-60-0 <- cdklabs-awscdkappsyncutils_0-0-152
amazon-jsii-runtime_1-85-0: Amazon.JSII.Runtime\nv1.85.0
amazon-jsii-runtime_1-85-0.style.fill: "#FFEC96"
amazon-jsii-runtime_1-85-0.style.opacity: 0.8
amazon-jsii-runtime_1-85-0 <- cdklabs-awscdkappsyncutils_0-0-152
constructs_10-0-5: Constructs\nv10.0.5
constructs_10-0-5.style.fill: "#FFEC96"
constructs_10-0-5.style.opacity: 0.8
constructs_10-0-5 <- cdklabs-awscdkappsyncutils_0-0-152
cdklabs-awscdkappsyncutils_0-0-152 <- aoi.alloverit-aws-cdk-appsync
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-aws-cdk-appsync
