direction: right

aoi: AllOverIt
aoi.alloverit-validation-options: AllOverIt.Validation.Options
aoi.alloverit-validation: AllOverIt.Validation
microsoft-extensions-options: Microsoft.Extensions.Options
microsoft-extensions-options.style.fill: lightblue
microsoft-extensions-options.style.opacity: 0.8

aoi.alloverit-validation <- aoi.alloverit-validation-options
microsoft-extensions-options <- aoi.alloverit-validation-options
