direction: right

aoi: AllOverIt
aoi.alloverit-entityframeworkcore-pagination: AllOverIt.EntityFrameworkCore.Pagination
aoi.alloverit-entityframeworkcore: AllOverIt.EntityFrameworkCore
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
microsoft-entityframeworkcore-relational: Microsoft.EntityFrameworkCore.Relational
microsoft-entityframeworkcore-relational.style.fill: lightblue
microsoft-entityframeworkcore-relational.style.opacity: 0.8
aoi.alloverit-pagination: AllOverIt.Pagination
aoi.alloverit-serialization-binary: AllOverIt.Serialization.Binary
microsoft-extensions-dependencyinjection-abstractions: Microsoft.Extensions.DependencyInjection.Abstractions
microsoft-extensions-dependencyinjection-abstractions.style.fill: lightblue
microsoft-extensions-dependencyinjection-abstractions.style.opacity: 0.8

aoi.alloverit-entityframeworkcore <- aoi.alloverit-entityframeworkcore-pagination
aoi.alloverit <- aoi.alloverit-entityframeworkcore
aoi.alloverit-assertion <- aoi.alloverit
microsoft-entityframeworkcore-relational <- aoi.alloverit-entityframeworkcore
aoi.alloverit-pagination <- aoi.alloverit-entityframeworkcore-pagination
aoi.alloverit-serialization-binary <- aoi.alloverit-pagination
aoi.alloverit <- aoi.alloverit-serialization-binary
aoi.alloverit-assertion <- aoi.alloverit
microsoft-extensions-dependencyinjection-abstractions <- aoi.alloverit-pagination
