direction: right

aoi: AllOverIt
aoi.alloverit-aws-appsync-client: AllOverIt.Aws.AppSync.Client
microsoft-extensions-dependencyinjection: Microsoft.Extensions.DependencyInjection
microsoft-extensions-dependencyinjection.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions: Microsoft.Extensions.DependencyInjection.Abstractions
microsoft-extensions-dependencyinjection-abstractions.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection-abstractions.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions <- microsoft-extensions-dependencyinjection
microsoft-extensions-dependencyinjection <- aoi.alloverit-aws-appsync-client
microsoft-extensions-http: Microsoft.Extensions.Http
microsoft-extensions-http.style.fill: "#ADD8E6"
microsoft-extensions-http.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions <- microsoft-extensions-http
microsoft-extensions-logging-abstractions: Microsoft.Extensions.Logging.Abstractions
microsoft-extensions-logging-abstractions.style.fill: "#FFEC96"
microsoft-extensions-logging-abstractions.style.opacity: 0.8
microsoft-extensions-logging-abstractions <- microsoft-extensions-http
microsoft-extensions-logging: Microsoft.Extensions.Logging
microsoft-extensions-logging.style.fill: "#FFEC96"
microsoft-extensions-logging.style.opacity: 0.8
microsoft-extensions-logging <- microsoft-extensions-http
microsoft-extensions-options: Microsoft.Extensions.Options
microsoft-extensions-options.style.fill: "#FFEC96"
microsoft-extensions-options.style.opacity: 0.8
microsoft-extensions-options <- microsoft-extensions-http
microsoft-extensions-http <- aoi.alloverit-aws-appsync-client
aoi.alloverit-reactive: AllOverIt.Reactive
system-reactive: System.Reactive
system-reactive.style.fill: "#ADD8E6"
system-reactive.style.opacity: 0.8
system-threading-tasks-extensions: System.Threading.Tasks.Extensions
system-threading-tasks-extensions.style.fill: "#FFEC96"
system-threading-tasks-extensions.style.opacity: 0.8
system-threading-tasks-extensions <- system-reactive
system-reactive <- aoi.alloverit-reactive
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-reactive
aoi.alloverit-reactive <- aoi.alloverit-aws-appsync-client
aoi.alloverit-serialization-json-abstractions: AllOverIt.Serialization.Json.Abstractions
aoi.alloverit <- aoi.alloverit-serialization-json-abstractions
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-aws-appsync-client
