direction: right

aoi: AllOverIt
aoi.alloverit-pipes-serialization-binary: AllOverIt.Pipes.Serialization.Binary
aoi.alloverit-pipes-serialization: AllOverIt.Pipes.Serialization
aoi.alloverit-pipes-serialization <- aoi.alloverit-pipes-serialization-binary
aoi.alloverit-serialization-binary: AllOverIt.Serialization.Binary
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-serialization-binary
aoi.alloverit-serialization-binary <- aoi.alloverit-pipes-serialization-binary
