direction: right

aoi: AllOverIt
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit-aspnetcore: AllOverIt.AspNetCore
microsoft-aspnetcore-mvc: Microsoft.AspNetCore.Mvc
microsoft-aspnetcore-mvc.style.fill: "#ADD8E6"
microsoft-aspnetcore-mvc.style.opacity: 0.8
microsoft-aspnetcore-mvc <- aoi.alloverit-aspnetcore
aoi.alloverit <- aoi.alloverit-aspnetcore
aoi.alloverit-aws-appsync-client: AllOverIt.Aws.AppSync.Client
microsoft-extensions-dependencyinjection: Microsoft.Extensions.DependencyInjection
microsoft-extensions-dependencyinjection.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection.style.opacity: 0.8
microsoft-extensions-dependencyinjection <- aoi.alloverit-aws-appsync-client
microsoft-extensions-http: Microsoft.Extensions.Http
microsoft-extensions-http.style.fill: "#ADD8E6"
microsoft-extensions-http.style.opacity: 0.8
microsoft-extensions-http <- aoi.alloverit-aws-appsync-client
aoi.alloverit-reactive: AllOverIt.Reactive
system-reactive: System.Reactive
system-reactive.style.fill: "#ADD8E6"
system-reactive.style.opacity: 0.8
system-reactive <- aoi.alloverit-reactive
aoi.alloverit <- aoi.alloverit-reactive
aoi.alloverit-reactive <- aoi.alloverit-aws-appsync-client
aoi.alloverit-serialization-json-abstractions: AllOverIt.Serialization.Json.Abstractions
aoi.alloverit <- aoi.alloverit-serialization-json-abstractions
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-aws-appsync-client
aoi.alloverit-aws-cdk-appsync: AllOverIt.Aws.Cdk.AppSync
amazon-cdk-aws-appsync: Amazon.CDK.AWS.AppSync
amazon-cdk-aws-appsync.style.fill: "#ADD8E6"
amazon-cdk-aws-appsync.style.opacity: 0.8
amazon-cdk-aws-appsync <- aoi.alloverit-aws-cdk-appsync
aoi.alloverit <- aoi.alloverit-aws-cdk-appsync
aoi.alloverit-csv: AllOverIt.Csv
csvhelper: CsvHelper
csvhelper.style.fill: "#ADD8E6"
csvhelper.style.opacity: 0.8
csvhelper <- aoi.alloverit-csv
aoi.alloverit <- aoi.alloverit-csv
aoi.alloverit-dependencyinjection: AllOverIt.DependencyInjection
microsoft-extensions-dependencyinjection-abstractions: Microsoft.Extensions.DependencyInjection.Abstractions
microsoft-extensions-dependencyinjection-abstractions.style.fill: "#ADD8E6"
microsoft-extensions-dependencyinjection-abstractions.style.opacity: 0.8
microsoft-extensions-dependencyinjection-abstractions <- aoi.alloverit-dependencyinjection
aoi.alloverit <- aoi.alloverit-dependencyinjection
aoi.alloverit-entityframeworkcore: AllOverIt.EntityFrameworkCore
microsoft-entityframeworkcore-relational: Microsoft.EntityFrameworkCore.Relational
microsoft-entityframeworkcore-relational.style.fill: "#ADD8E6"
microsoft-entityframeworkcore-relational.style.opacity: 0.8
microsoft-entityframeworkcore-relational <- aoi.alloverit-entityframeworkcore
aoi.alloverit <- aoi.alloverit-entityframeworkcore
aoi.alloverit-entityframeworkcore-diagrams: AllOverIt.EntityFrameworkCore.Diagrams
microsoft-entityframeworkcore-relational <- aoi.alloverit-entityframeworkcore-diagrams
aoi.alloverit <- aoi.alloverit-entityframeworkcore-diagrams
aoi.alloverit-entityframeworkcore-pagination: AllOverIt.EntityFrameworkCore.Pagination
aoi.alloverit-entityframeworkcore <- aoi.alloverit-entityframeworkcore-pagination
aoi.alloverit-pagination: AllOverIt.Pagination
microsoft-extensions-dependencyinjection-abstractions <- aoi.alloverit-pagination
aoi.alloverit-serialization-binary: AllOverIt.Serialization.Binary
aoi.alloverit <- aoi.alloverit-serialization-binary
aoi.alloverit-serialization-binary <- aoi.alloverit-pagination
aoi.alloverit-pagination <- aoi.alloverit-entityframeworkcore-pagination
aoi.alloverit-evaluator: AllOverIt.Evaluator
aoi.alloverit <- aoi.alloverit-evaluator
aoi.alloverit-filtering: AllOverIt.Filtering
aoi.alloverit <- aoi.alloverit-filtering
aoi.alloverit-fixture: AllOverIt.Fixture
autofixture: AutoFixture
autofixture.style.fill: "#ADD8E6"
autofixture.style.opacity: 0.8
autofixture <- aoi.alloverit-fixture
fluentassertions: FluentAssertions
fluentassertions.style.fill: "#ADD8E6"
fluentassertions.style.opacity: 0.8
fluentassertions <- aoi.alloverit-fixture
aoi.alloverit-fixture-fakeiteasy: AllOverIt.Fixture.FakeItEasy
autofixture-autofakeiteasy: AutoFixture.AutoFakeItEasy
autofixture-autofakeiteasy.style.fill: "#ADD8E6"
autofixture-autofakeiteasy.style.opacity: 0.8
autofixture-autofakeiteasy <- aoi.alloverit-fixture-fakeiteasy
fakeiteasy: FakeItEasy
fakeiteasy.style.fill: "#ADD8E6"
fakeiteasy.style.opacity: 0.8
fakeiteasy <- aoi.alloverit-fixture-fakeiteasy
aoi.alloverit-fixture <- aoi.alloverit-fixture-fakeiteasy
aoi.alloverit-generichost: AllOverIt.GenericHost
microsoft-extensions-hosting: Microsoft.Extensions.Hosting
microsoft-extensions-hosting.style.fill: "#ADD8E6"
microsoft-extensions-hosting.style.opacity: 0.8
microsoft-extensions-hosting <- aoi.alloverit-generichost
aoi.alloverit <- aoi.alloverit-generichost
aoi.alloverit-mapping: AllOverIt.Mapping
aoi.alloverit <- aoi.alloverit-mapping
aoi.alloverit-reactiveui: AllOverIt.ReactiveUI
microsoft-extensions-dependencyinjection-abstractions <- aoi.alloverit-reactiveui
reactiveui: ReactiveUI
reactiveui.style.fill: "#ADD8E6"
reactiveui.style.opacity: 0.8
reactiveui <- aoi.alloverit-reactiveui
aoi.alloverit <- aoi.alloverit-reactiveui
aoi.alloverit-serialization-json-newtonsoft: AllOverIt.Serialization.Json.Newtonsoft
newtonsoft-json: Newtonsoft.Json
newtonsoft-json.style.fill: "#ADD8E6"
newtonsoft-json.style.opacity: 0.8
newtonsoft-json <- aoi.alloverit-serialization-json-newtonsoft
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-serialization-json-newtonsoft
aoi.alloverit-serialization-json-systemtext: AllOverIt.Serialization.Json.SystemText
system-text-json: System.Text.Json
system-text-json.style.fill: "#ADD8E6"
system-text-json.style.opacity: 0.8
system-text-json <- aoi.alloverit-serialization-json-systemtext
aoi.alloverit-serialization-json-abstractions <- aoi.alloverit-serialization-json-systemtext
aoi.alloverit-validation: AllOverIt.Validation
fluentvalidation: FluentValidation
fluentvalidation.style.fill: "#ADD8E6"
fluentvalidation.style.opacity: 0.8
fluentvalidation <- aoi.alloverit-validation
aoi.alloverit <- aoi.alloverit-validation
aoi.alloverit-validation-options: AllOverIt.Validation.Options
microsoft-extensions-options: Microsoft.Extensions.Options
microsoft-extensions-options.style.fill: "#ADD8E6"
microsoft-extensions-options.style.opacity: 0.8
microsoft-extensions-options <- aoi.alloverit-validation-options
aoi.alloverit-validation <- aoi.alloverit-validation-options
aoi.alloverit-wpf: AllOverIt.Wpf
aoi.alloverit <- aoi.alloverit-wpf
aoi.alloverit-wpf-controls: AllOverIt.Wpf.Controls
aoi.alloverit <- aoi.alloverit-wpf-controls
