direction: right

aoi: AllOverIt
aoi.alloverit-generichost: AllOverIt.GenericHost
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
microsoft-extensions-hosting: Microsoft.Extensions.Hosting
microsoft-extensions-hosting.style.fill: lightblue
microsoft-extensions-hosting.style.opacity: 0.8

aoi.alloverit <- aoi.alloverit-generichost
aoi.alloverit-assertion <- aoi.alloverit
microsoft-extensions-hosting <- aoi.alloverit-generichost
