direction: right

aoi: AllOverIt
aoi.alloverit-csv: AllOverIt.Csv
aoi.alloverit: AllOverIt
csvhelper: CsvHelper
csvhelper.style.fill: lightblue
csvhelper.style.opacity: 0.8

aoi.alloverit <- aoi.alloverit-csv
csvhelper <- aoi.alloverit-csv
