direction: right

aoi: AllOverIt
aoi.alloverit-validation: AllOverIt.Validation
fluentvalidation_11-5-2: FluentValidation\nv11.5.2
fluentvalidation_11-5-2.style.fill: "#ADD8E6"
fluentvalidation_11-5-2.style.opacity: 0.8
fluentvalidation_11-5-2 <- aoi.alloverit-validation
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-validation
