direction: right

aoi: AllOverIt
aoi.alloverit-aspnetcore: AllOverIt.AspNetCore
microsoft-aspnetcore-mvc_2-2-0: Microsoft.AspNetCore.Mvc\nv2.2.0
microsoft-aspnetcore-mvc_2-2-0.style.fill: "#ADD8E6"
microsoft-aspnetcore-mvc_2-2-0.style.opacity: 0.8
microsoft-aspnetcore-mvc-analyzers_2-2-0: Microsoft.AspNetCore.Mvc.Analyzers\nv2.2.0
microsoft-aspnetcore-mvc-analyzers_2-2-0.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-analyzers_2-2-0.style.opacity: 0.8
microsoft-aspnetcore-mvc-analyzers_2-2-0 <- microsoft-aspnetcore-mvc_2-2-0
microsoft-aspnetcore-mvc-apiexplorer_2-2-0: Microsoft.AspNetCore.Mvc.ApiExplorer\nv2.2.0
microsoft-aspnetcore-mvc-apiexplorer_2-2-0.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-apiexplorer_2-2-0.style.opacity: 0.8
microsoft-aspnetcore-mvc-apiexplorer_2-2-0 <- microsoft-aspnetcore-mvc_2-2-0
microsoft-aspnetcore-mvc-cors_2-2-0: Microsoft.AspNetCore.Mvc.Cors\nv2.2.0
microsoft-aspnetcore-mvc-cors_2-2-0.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-cors_2-2-0.style.opacity: 0.8
microsoft-aspnetcore-mvc-cors_2-2-0 <- microsoft-aspnetcore-mvc_2-2-0
microsoft-aspnetcore-mvc-dataannotations_2-2-0: Microsoft.AspNetCore.Mvc.DataAnnotations\nv2.2.0
microsoft-aspnetcore-mvc-dataannotations_2-2-0.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-dataannotations_2-2-0.style.opacity: 0.8
microsoft-aspnetcore-mvc-dataannotations_2-2-0 <- microsoft-aspnetcore-mvc_2-2-0
microsoft-aspnetcore-mvc-formatters-json_2-2-0: Microsoft.AspNetCore.Mvc.Formatters.Json\nv2.2.0
microsoft-aspnetcore-mvc-formatters-json_2-2-0.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-formatters-json_2-2-0.style.opacity: 0.8
microsoft-aspnetcore-mvc-formatters-json_2-2-0 <- microsoft-aspnetcore-mvc_2-2-0
microsoft-aspnetcore-mvc-localization_2-2-0: Microsoft.AspNetCore.Mvc.Localization\nv2.2.0
microsoft-aspnetcore-mvc-localization_2-2-0.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-localization_2-2-0.style.opacity: 0.8
microsoft-aspnetcore-mvc-localization_2-2-0 <- microsoft-aspnetcore-mvc_2-2-0
microsoft-aspnetcore-mvc-razorpages_2-2-0: Microsoft.AspNetCore.Mvc.RazorPages\nv2.2.0
microsoft-aspnetcore-mvc-razorpages_2-2-0.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-razorpages_2-2-0.style.opacity: 0.8
microsoft-aspnetcore-mvc-razorpages_2-2-0 <- microsoft-aspnetcore-mvc_2-2-0
microsoft-aspnetcore-mvc-taghelpers_2-2-0: Microsoft.AspNetCore.Mvc.TagHelpers\nv2.2.0
microsoft-aspnetcore-mvc-taghelpers_2-2-0.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-taghelpers_2-2-0.style.opacity: 0.8
microsoft-aspnetcore-mvc-taghelpers_2-2-0 <- microsoft-aspnetcore-mvc_2-2-0
microsoft-aspnetcore-mvc-viewfeatures_2-2-0: Microsoft.AspNetCore.Mvc.ViewFeatures\nv2.2.0
microsoft-aspnetcore-mvc-viewfeatures_2-2-0.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-viewfeatures_2-2-0.style.opacity: 0.8
microsoft-aspnetcore-mvc-viewfeatures_2-2-0 <- microsoft-aspnetcore-mvc_2-2-0
microsoft-aspnetcore-mvc-razor-extensions_2-2-0: Microsoft.AspNetCore.Mvc.Razor.Extensions\nv2.2.0
microsoft-aspnetcore-mvc-razor-extensions_2-2-0.style.fill: "#FFEC96"
microsoft-aspnetcore-mvc-razor-extensions_2-2-0.style.opacity: 0.8
microsoft-aspnetcore-mvc-razor-extensions_2-2-0 <- microsoft-aspnetcore-mvc_2-2-0
microsoft-aspnetcore-razor-design_2-2-0: Microsoft.AspNetCore.Razor.Design\nv2.2.0
microsoft-aspnetcore-razor-design_2-2-0.style.fill: "#FFEC96"
microsoft-aspnetcore-razor-design_2-2-0.style.opacity: 0.8
microsoft-aspnetcore-razor-design_2-2-0 <- microsoft-aspnetcore-mvc_2-2-0
microsoft-extensions-caching-memory_2-2-0: Microsoft.Extensions.Caching.Memory\nv2.2.0
microsoft-extensions-caching-memory_2-2-0.style.fill: "#FFEC96"
microsoft-extensions-caching-memory_2-2-0.style.opacity: 0.8
microsoft-extensions-caching-memory_2-2-0 <- microsoft-aspnetcore-mvc_2-2-0
microsoft-extensions-dependencyinjection_2-2-0: Microsoft.Extensions.DependencyInjection\nv2.2.0
microsoft-extensions-dependencyinjection_2-2-0.style.fill: "#FFEC96"
microsoft-extensions-dependencyinjection_2-2-0.style.opacity: 0.8
microsoft-extensions-dependencyinjection_2-2-0 <- microsoft-aspnetcore-mvc_2-2-0
microsoft-aspnetcore-mvc_2-2-0 <- aoi.alloverit-aspnetcore
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-aspnetcore
