direction: right

aoi: AllOverIt
aoi.alloverit-fixture: AllOverIt.Fixture
autofixture: AutoFixture
autofixture.style.fill: lightblue
autofixture.style.opacity: 0.8
fare: Fare
fare.style.fill: lightblue
fare.style.opacity: 0.8
system-componentmodel-annotations: System.ComponentModel.Annotations
system-componentmodel-annotations.style.fill: lightblue
system-componentmodel-annotations.style.opacity: 0.8
fluentassertions: FluentAssertions
fluentassertions.style.fill: lightblue
fluentassertions.style.opacity: 0.8

autofixture <- aoi.alloverit-fixture
fare <- autofixture
system-componentmodel-annotations <- autofixture
fluentassertions <- aoi.alloverit-fixture
