direction: right

aoi: AllOverIt
aoi.alloverit-validation: AllOverIt.Validation
fluentvalidation_11-6-0: FluentValidation\nv11.6.0
fluentvalidation_11-6-0.style.fill: "#ADD8E6"
fluentvalidation_11-6-0.style.opacity: 0.8
fluentvalidation_11-6-0 <- aoi.alloverit-validation
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-validation
