direction: right

aoi: AllOverIt
aoi.alloverit-aspnetcore: AllOverIt.AspNetCore
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
aoi.alloverit-assertion <- aoi.alloverit
aoi.alloverit <- aoi.alloverit-aspnetcore
