direction: right

aoi: AllOverIt
aoi.alloverit-csv: AllOverIt.Csv
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion
csvhelper: CsvHelper
csvhelper.style.fill: lightblue
csvhelper.style.opacity: 0.8

aoi.alloverit <- aoi.alloverit-csv
aoi.alloverit-assertion <- aoi.alloverit
csvhelper <- aoi.alloverit-csv
