direction: right

aoi: AllOverIt
aoi.alloverit-serialization-binary: AllOverIt.Serialization.Binary
aoi.alloverit: AllOverIt
aoi.alloverit-assertion: AllOverIt.Assertion

aoi.alloverit <- aoi.alloverit-serialization-binary
aoi.alloverit-assertion <- aoi.alloverit
