Author: {
  shape: sql_table

  Id: INTEGER \[NOT NULL\] {constraint: primary_key}
  Email: TEXT(50) \[NOT NULL\]
  FirstName: TEXT(50) \[NOT NULL\]
  LastName: TEXT(50)
}

AuthorBlog: {
  shape: sql_table

  Id: INTEGER \[NOT NULL\] {constraint: primary_key}
  AuthorId: INTEGER \[NOT NULL\] {constraint: foreign_key}
  BlogId: INTEGER \[NOT NULL\] {constraint: foreign_key}
}

Blog: {
  shape: sql_table

  Id: INTEGER \[NOT NULL\] {constraint: primary_key}
  Description: TEXT(500) \[NOT NULL\]
  WebSiteId: INTEGER \[NOT NULL\] {constraint: foreign_key}
}

Comment: {
  shape: sql_table

  Id: INTEGER \[NOT NULL\] {constraint: primary_key}
  AuthorId: INTEGER \[NOT NULL\] {constraint: foreign_key}
  Content: TEXT \[NOT NULL\]
  PostId: INTEGER \[NOT NULL\] {constraint: foreign_key}
}

Post: {
  shape: sql_table

  Id: INTEGER \[NOT NULL\] {constraint: primary_key}
  BlogId: INTEGER \[NOT NULL\] {constraint: foreign_key}
  Content: TEXT \[NOT NULL\]
  Title: TEXT(500) \[NOT NULL\]
}

Settings: {
  shape: sql_table

  Id: INTEGER \[NOT NULL\] {constraint: primary_key}
  JsonConfig: TEXT \[NOT NULL\]
  WebSiteId: INTEGER \[NOT NULL\] {constraint: foreign_key}
}

WebSite: {
  shape: sql_table

  Id: INTEGER \[NOT NULL\] {constraint: primary_key}
  Description: TEXT(500) \[NOT NULL\]
}

Author.Id -> AuthorBlog.AuthorId: ONE-TO-MANY {
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

Blog.Id -> AuthorBlog.BlogId: ONE-TO-MANY {
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

WebSite.Id -> Blog.WebSiteId: ONE-TO-MANY {
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

Author.Id -> Comment.AuthorId: ONE-TO-MANY {
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

Post.Id -> Comment.PostId: ONE-TO-MANY {
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

Blog.Id -> Post.BlogId: ONE-TO-MANY {
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}

WebSite.Id -> Settings.WebSiteId: ONE-TO-ONE {
  style: {
    font-size: 18
    font-color: blue
    bold: true
  }
}
